import type { ITheme } from "@xterm/xterm";

export interface TerminalThemeDefinition {
  id: string;
  name: string;
  variant: "dark" | "light";
  theme: ITheme;
}

export const TERMINAL_THEME_DEFINITIONS: TerminalThemeDefinition[] = [
  {
    id: "classic",
    name: "MobaXterm Classic",
    variant: "dark",
    theme: {
      background: "#1d1f21",
      foreground: "#eaeaea",
      cursor: "#f5e0dc",
      selectionBackground: "#44475a",
      black: "#1d1f21",
      red: "#ff6b6b",
      green: "#62d36f",
      yellow: "#e3a85e",
      blue: "#83a7d8",
      magenta: "#c792ea",
      cyan: "#89ddff",
      white: "#eaeaea",
    },
  },
  {
    id: "termius-dark",
    name: "Termius Dark",
    variant: "dark",
    theme: {
      background: "#101420",
      foreground: "#d7dde8",
      cursor: "#00d492",
      selectionBackground: "#283241",
      black: "#1b2230",
      red: "#ff5c7a",
      green: "#00c986",
      yellow: "#ffc861",
      blue: "#6ea8ff",
      magenta: "#c58cff",
      cyan: "#2dd4bf",
      white: "#d7dde8",
    },
  },
  {
    id: "termius-light",
    name: "Termius Light",
    variant: "light",
    theme: {
      background: "#eef3f7",
      foreground: "#1d2633",
      cursor: "#16846b",
      selectionBackground: "#c9d6e3",
      black: "#334155",
      red: "#cc334e",
      green: "#16846b",
      yellow: "#a66b00",
      blue: "#3765a8",
      magenta: "#8b4cb8",
      cyan: "#167a8a",
      white: "#f8fafc",
    },
  },
  {
    id: "flexoki-dark",
    name: "Flexoki Dark",
    variant: "dark",
    theme: {
      background: "#100f0f",
      foreground: "#cecdc3",
      cursor: "#cecdc3",
      selectionBackground: "#403e3c",
      black: "#282726",
      red: "#af3029",
      green: "#66800b",
      yellow: "#ad8301",
      blue: "#205ea6",
      magenta: "#a02f6f",
      cyan: "#24837b",
      white: "#cecdc3",
    },
  },
  {
    id: "flexoki-light",
    name: "Flexoki Light",
    variant: "light",
    theme: {
      background: "#fffcf0",
      foreground: "#100f0f",
      cursor: "#100f0f",
      selectionBackground: "#e6e4d9",
      black: "#403e3c",
      red: "#af3029",
      green: "#66800b",
      yellow: "#ad8301",
      blue: "#205ea6",
      magenta: "#a02f6f",
      cyan: "#24837b",
      white: "#fffcf0",
    },
  },
  {
    id: "kanagawa-wave",
    name: "Kanagawa Wave",
    variant: "dark",
    theme: {
      background: "#1f1f28",
      foreground: "#dcd7ba",
      cursor: "#c8c093",
      selectionBackground: "#2d4f67",
      black: "#16161d",
      red: "#c34043",
      green: "#76946a",
      yellow: "#c0a36e",
      blue: "#7e9cd8",
      magenta: "#957fb8",
      cyan: "#6a9589",
      white: "#dcd7ba",
    },
  },
  {
    id: "kanagawa-dragon",
    name: "Kanagawa Dragon",
    variant: "dark",
    theme: {
      background: "#181616",
      foreground: "#c5c9c5",
      cursor: "#c5c9c5",
      selectionBackground: "#2d4f67",
      black: "#0d0c0c",
      red: "#c4746e",
      green: "#8a9a7b",
      yellow: "#c4b28a",
      blue: "#8ba4b0",
      magenta: "#a292a3",
      cyan: "#8ea4a2",
      white: "#c5c9c5",
    },
  },
  {
    id: "kanagawa-lotus",
    name: "Kanagawa Lotus",
    variant: "light",
    theme: {
      background: "#f2ecbc",
      foreground: "#545464",
      cursor: "#545464",
      selectionBackground: "#d5cea3",
      black: "#1f1f28",
      red: "#c84053",
      green: "#6f894e",
      yellow: "#77713f",
      blue: "#4d699b",
      magenta: "#b35b79",
      cyan: "#597b75",
      white: "#f2ecbc",
    },
  },
  {
    id: "hacker-blue",
    name: "Hacker Blue",
    variant: "dark",
    theme: {
      background: "#061724",
      foreground: "#bfeeff",
      cursor: "#00c8ff",
      selectionBackground: "#123c54",
      black: "#00131f",
      red: "#ff5277",
      green: "#29e6a7",
      yellow: "#f2ff7a",
      blue: "#00b7ff",
      magenta: "#7b61ff",
      cyan: "#22e7ff",
      white: "#d8fbff",
    },
  },
  {
    id: "hacker-green",
    name: "Hacker Green",
    variant: "dark",
    theme: {
      background: "#031306",
      foreground: "#b7ffbf",
      cursor: "#00ff66",
      selectionBackground: "#123d1d",
      black: "#001f08",
      red: "#ff3b5f",
      green: "#00e64d",
      yellow: "#ccff66",
      blue: "#39a6ff",
      magenta: "#b266ff",
      cyan: "#4dffc9",
      white: "#e8ffe8",
    },
  },
  {
    id: "hacker-red",
    name: "Hacker Red",
    variant: "dark",
    theme: {
      background: "#260206",
      foreground: "#ffd6d6",
      cursor: "#ff204e",
      selectionBackground: "#5c0d18",
      black: "#150004",
      red: "#ff204e",
      green: "#70e000",
      yellow: "#ffd166",
      blue: "#4cc9f0",
      magenta: "#f72585",
      cyan: "#00f5d4",
      white: "#ffe5e5",
    },
  },
  {
    id: "everforest-dark",
    name: "Everforest Dark",
    variant: "dark",
    theme: {
      background: "#232a2e",
      foreground: "#d3c6aa",
      cursor: "#d3c6aa",
      selectionBackground: "#3c4841",
      black: "#2d353b",
      red: "#e67e80",
      green: "#a7c080",
      yellow: "#dbbc7f",
      blue: "#7fbbb3",
      magenta: "#d699b6",
      cyan: "#83c092",
      white: "#d3c6aa",
    },
  },
  {
    id: "everforest-light",
    name: "Everforest Light",
    variant: "light",
    theme: {
      background: "#fdf6e3",
      foreground: "#5c6a72",
      cursor: "#5c6a72",
      selectionBackground: "#e8e1c8",
      black: "#5c6a72",
      red: "#f85552",
      green: "#8da101",
      yellow: "#dfa000",
      blue: "#3a94c5",
      magenta: "#df69ba",
      cyan: "#35a77c",
      white: "#fdf6e3",
    },
  },
  {
    id: "night-owl",
    name: "Night Owl",
    variant: "dark",
    theme: {
      background: "#011627",
      foreground: "#d6deeb",
      cursor: "#80a4c2",
      selectionBackground: "#1d3b53",
      black: "#011627",
      red: "#ef5350",
      green: "#22da6e",
      yellow: "#addb67",
      blue: "#82aaff",
      magenta: "#c792ea",
      cyan: "#21c7a8",
      white: "#d6deeb",
    },
  },
];

const legacyAliases: Record<string, string> = {
  dark: "termius-dark",
  light: "termius-light",
};

export const terminalThemes: Record<string, ITheme> = {
  ...Object.fromEntries(TERMINAL_THEME_DEFINITIONS.map((definition) => [definition.id, definition.theme])),
  dark: TERMINAL_THEME_DEFINITIONS.find((definition) => definition.id === legacyAliases.dark)?.theme
    ?? TERMINAL_THEME_DEFINITIONS[0].theme,
  light: TERMINAL_THEME_DEFINITIONS.find((definition) => definition.id === legacyAliases.light)?.theme
    ?? TERMINAL_THEME_DEFINITIONS[0].theme,
};

export function resolveThemeId(theme: string): string {
  return legacyAliases[theme] ?? theme;
}

export function getTerminalThemeDefinition(theme: string): TerminalThemeDefinition | undefined {
  const resolved = resolveThemeId(theme);
  return TERMINAL_THEME_DEFINITIONS.find((definition) => definition.id === resolved);
}
