#!/usr/bin/env python3
"""Verify one installed Linux Sockscap package and emit release evidence.

Lint mode validates the disabled manifest and committed fixed policy without
requiring root, package tools, signatures, or installed artifacts. Release
mode is intentionally same-host: it verifies the exact package signature and
payload, then re-hashes and inspects the fixed installed paths before emitting
a receipt. It does not prove native install/uninstall lab provenance; that
evidence remains an external Gate input. Capture releases are restricted to
the fixed DEB/RPM contract: ordinary AppImage and updater artifacts must keep
capture disabled.
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass
import errno
import hashlib
import json
import os
from pathlib import Path, PurePosixPath
import re
import stat
import subprocess
import sys
import tarfile
import tempfile
from typing import Any, Callable, Iterable
import xml.etree.ElementTree as ElementTree


POLICY_SCHEMA_VERSION = 1
MANIFEST_SCHEMA_VERSION = 1
RECEIPT_SCHEMA_VERSION = 1
PACKAGE_MANIFEST_SCHEMA_VERSION = 1
PLATFORM = "linux"
CAPTURE_PROVIDER = "cgroup_v2_nft_tun"
SUPPORTED_ARCHITECTURES = {"x86_64", "aarch64"}
PACKAGE_KINDS = {"deb", "rpm"}
CAPTURE_PACKAGE_KINDS = ("deb", "rpm")
PACKAGE_DEPENDENCIES = {
    "deb": ("iproute2", "nftables", "policykit-1"),
    "rpm": ("iproute", "nftables", "polkit"),
}
PACKAGE_DESKTOP_FILES = ("/usr/share/applications/Taomni.desktop",)
PACKAGE_ICON_FILES = (
    "/usr/share/icons/hicolor/32x32/apps/taomni.png",
    "/usr/share/icons/hicolor/128x128/apps/taomni.png",
    "/usr/share/icons/hicolor/256x256@2/apps/taomni.png",
)
PACKAGE_SCRIPT_NORMALIZATION = "utf8_lf_single_terminal_newline_v1"
PACKAGE_SCRIPT_NAMES = ("require-clean-state", "post-install", "post-remove")
PACKAGE_SCRIPT_MAPPINGS = {
    "deb": {
        "preinst": "require-clean-state",
        "prerm": "require-clean-state",
        "postinst": "post-install",
        "postrm": "post-remove",
    },
    "rpm": {
        "pre": "require-clean-state",
        "preun": "require-clean-state",
        "post": "post-install",
        "postun": "post-remove",
    },
}
RPM_SCRIPT_QUERY_TAGS = {
    "pre": ("PREIN", "PREINPROG"),
    "preun": ("PREUN", "PREUNPROG"),
    "post": ("POSTIN", "POSTINPROG"),
    "postun": ("POSTUN", "POSTUNPROG"),
}
RPM_FORBIDDEN_PRIMARY_SCRIPT_FLAGS = (
    "PREINFLAGS",
    "PREUNFLAGS",
    "POSTINFLAGS",
    "POSTUNFLAGS",
)
RPM_FORBIDDEN_SCRIPT_TAGS = (
    "PRETRANS",
    "PRETRANSPROG",
    "PRETRANSFLAGS",
    "POSTTRANS",
    "POSTTRANSPROG",
    "POSTTRANSFLAGS",
    "PREUNTRANS",
    "PREUNTRANSPROG",
    "PREUNTRANSFLAGS",
    "POSTUNTRANS",
    "POSTUNTRANSPROG",
    "POSTUNTRANSFLAGS",
    "VERIFYSCRIPT",
    "VERIFYSCRIPTPROG",
    "VERIFYSCRIPTFLAGS",
    "TRIGGERSCRIPTS",
    "TRIGGERSCRIPTPROG",
    "TRIGGERSCRIPTFLAGS",
    "TRIGGERNAME",
    "TRIGGERVERSION",
    "TRIGGERFLAGS",
    "TRIGGERINDEX",
    "FILETRIGGERSCRIPTS",
    "FILETRIGGERSCRIPTPROG",
    "FILETRIGGERSCRIPTFLAGS",
    "FILETRIGGERNAME",
    "FILETRIGGERVERSION",
    "FILETRIGGERFLAGS",
    "FILETRIGGERINDEX",
    "FILETRIGGERPRIORITIES",
    "TRANSFILETRIGGERSCRIPTS",
    "TRANSFILETRIGGERSCRIPTPROG",
    "TRANSFILETRIGGERSCRIPTFLAGS",
    "TRANSFILETRIGGERNAME",
    "TRANSFILETRIGGERVERSION",
    "TRANSFILETRIGGERFLAGS",
    "TRANSFILETRIGGERINDEX",
    "TRANSFILETRIGGERPRIORITIES",
    "SYSUSERS",
)
RPM_FORBIDDEN_SEMANTIC_TAGS = (
    "POLICIES",
    "POLICYNAMES",
    "POLICYFLAGS",
    "POLICYTYPES",
    "POLICYTYPESINDEXES",
    "RECOMMENDNAME",
    "RECOMMENDVERSION",
    "RECOMMENDFLAGS",
    "SUGGESTNAME",
    "SUGGESTVERSION",
    "SUGGESTFLAGS",
    "SUPPLEMENTNAME",
    "SUPPLEMENTVERSION",
    "SUPPLEMENTFLAGS",
    "ENHANCENAME",
    "ENHANCEVERSION",
    "ENHANCEFLAGS",
    "CONFLICTNAME",
    "CONFLICTVERSION",
    "CONFLICTFLAGS",
    "OBSOLETENAME",
    "OBSOLETEVERSION",
    "OBSOLETEFLAGS",
    "ORDERNAME",
    "ORDERVERSION",
    "ORDERFLAGS",
)
RPM_ALLOWED_AUTOGENERATED_REQUIREMENTS = {
    "/bin/sh",
    "rpmlib(CompressedFileNames) <= 3.0.4-1",
    "rpmlib(FileDigests) <= 4.6.0-1",
    "rpmlib(PayloadFilesHavePrefix) <= 4.0-1",
    "rpmlib(PayloadIsXz) <= 5.2-1",
    "rpmlib(PayloadIsZstd) <= 5.4.18-1",
}
DEB_ALLOWED_CONTROL_MEMBERS = {"control", "md5sums"}
DEB_FORBIDDEN_RELATIONSHIP_FIELDS = (
    "Pre-Depends",
    "Recommends",
    "Suggests",
    "Enhances",
    "Conflicts",
    "Breaks",
    "Replaces",
    "Provides",
    "Built-Using",
    "Static-Built-Using",
)
DEB_BOOLEAN_OR_DEFAULT_NO_FIELDS = ("Essential", "Protected", "Important", "Multi-Arch")
SHA256_RE = re.compile(r"^[0-9a-fA-F]{64}$")
COMMIT_RE = re.compile(r"^[0-9a-fA-F]{40}$")
BUILD_ID_RE = re.compile(r"^[A-Za-z0-9._-]{1,128}$")
FINGERPRINT_RE = re.compile(r"^(?:[0-9A-Fa-f]{40}|[0-9A-Fa-f]{64})$")
MAX_JSON_BYTES = 1024 * 1024
MAX_POLICY_BYTES = 64 * 1024
MAX_POLKIT_BYTES = 64 * 1024
MAX_PACKAGE_SCRIPT_BYTES = 1024 * 1024
CHUNK_BYTES = 1024 * 1024
ROLE_NAMES = ("application", "helper", "helperPolicy", "polkitAction")
FIXED_TOOL_DIRECTORIES = (Path("/usr/bin"), Path("/usr/sbin"), Path("/bin"), Path("/sbin"))


class LinuxGateError(RuntimeError):
    def __init__(self, code: str, message: str):
        super().__init__(f"{code}: {message}")
        self.code = code
        self.message = message


def fail(code: str, message: str) -> None:
    raise LinuxGateError(code, message)


@dataclass(frozen=True)
class StableFile:
    path: Path
    sha256: str
    size: int
    uid: int
    gid: int
    mode: int
    content: bytes | None = None
    file_capabilities: bytes | None = None
    device: int | None = None
    inode: int | None = None
    mtime_ns: int | None = None
    ctime_ns: int | None = None


def _same_file_identity(left: os.stat_result, right: os.stat_result) -> bool:
    return (
        left.st_dev,
        left.st_ino,
        left.st_size,
        left.st_mode,
        left.st_uid,
        left.st_gid,
        left.st_mtime_ns,
        left.st_ctime_ns,
    ) == (
        right.st_dev,
        right.st_ino,
        right.st_size,
        right.st_mode,
        right.st_uid,
        right.st_gid,
        right.st_mtime_ns,
        right.st_ctime_ns,
    )


def absolute_path(path: Path) -> Path:
    return Path(os.path.abspath(os.fspath(path)))


def ensure_no_symlink_components(path: Path, label: str) -> None:
    path = absolute_path(path)
    current = Path(path.anchor)
    for component in path.parts[1:]:
        current /= component
        try:
            metadata = os.lstat(current)
        except OSError as error:
            fail("LINUX_ARTIFACT_MISSING", f"cannot inspect {label} {current}: {error}")
        if stat.S_ISLNK(metadata.st_mode):
            fail("LINUX_ARTIFACT_SYMLINK", f"{label} contains symlink component {current}")


def read_stable_file(
    path: Path,
    label: str,
    *,
    capture_content: bool = False,
    capture_file_capabilities: bool = False,
    max_bytes: int | None = None,
) -> StableFile:
    path = absolute_path(path)
    ensure_no_symlink_components(path, label)
    flags = os.O_RDONLY | getattr(os, "O_CLOEXEC", 0) | getattr(os, "O_NOFOLLOW", 0)
    try:
        descriptor = os.open(path, flags)
    except OSError as error:
        fail("LINUX_ARTIFACT_UNREADABLE", f"cannot open {label} {path}: {error}")
    try:
        before = os.fstat(descriptor)
        if not stat.S_ISREG(before.st_mode) or before.st_size <= 0:
            fail("LINUX_ARTIFACT_TYPE_INVALID", f"{label} must be a non-empty regular file")
        if max_bytes is not None and before.st_size > max_bytes:
            fail("LINUX_ARTIFACT_SIZE_INVALID", f"{label} exceeds {max_bytes} bytes")
        digest = hashlib.sha256()
        captured = bytearray() if capture_content else None
        while True:
            try:
                chunk = os.read(descriptor, CHUNK_BYTES)
            except OSError as error:
                fail("LINUX_ARTIFACT_UNREADABLE", f"cannot read {label}: {error}")
            if not chunk:
                break
            digest.update(chunk)
            if captured is not None:
                captured.extend(chunk)
        capabilities = (
            read_file_capabilities(descriptor) if capture_file_capabilities else None
        )
        after = os.fstat(descriptor)
        if not _same_file_identity(before, after):
            fail("LINUX_ARTIFACT_CHANGED", f"{label} changed while it was being hashed")
        return StableFile(
            path=path,
            sha256=digest.hexdigest(),
            size=before.st_size,
            uid=before.st_uid,
            gid=before.st_gid,
            mode=stat.S_IMODE(before.st_mode),
            content=bytes(captured) if captured is not None else None,
            file_capabilities=capabilities,
            device=before.st_dev,
            inode=before.st_ino,
            mtime_ns=before.st_mtime_ns,
            ctime_ns=before.st_ctime_ns,
        )
    finally:
        os.close(descriptor)


def snapshot_stable_file(
    path: Path,
    label: str,
    snapshot_directory: Path,
    snapshot_name: str,
    *,
    max_bytes: int | None = None,
) -> tuple[StableFile, Path]:
    """Copy one stable source fd into a private verifier-owned snapshot."""
    path = absolute_path(path)
    ensure_no_symlink_components(path, label)
    source_flags = os.O_RDONLY | getattr(os, "O_CLOEXEC", 0) | getattr(os, "O_NOFOLLOW", 0)
    try:
        source = os.open(path, source_flags)
    except OSError as error:
        fail("LINUX_ARTIFACT_UNREADABLE", f"cannot open {label} {path}: {error}")
    snapshot_path = snapshot_directory / snapshot_name
    output = -1
    try:
        before = os.fstat(source)
        if not stat.S_ISREG(before.st_mode) or before.st_size <= 0:
            fail("LINUX_ARTIFACT_TYPE_INVALID", f"{label} must be a non-empty regular file")
        if max_bytes is not None and before.st_size > max_bytes:
            fail("LINUX_ARTIFACT_SIZE_INVALID", f"{label} exceeds {max_bytes} bytes")
        output = os.open(
            snapshot_path,
            os.O_WRONLY | os.O_CREAT | os.O_EXCL | getattr(os, "O_CLOEXEC", 0),
            0o600,
        )
        os.fchmod(output, 0o600)
        digest = hashlib.sha256()
        copied = 0
        while True:
            chunk = os.read(source, CHUNK_BYTES)
            if not chunk:
                break
            digest.update(chunk)
            copied += len(chunk)
            pending = memoryview(chunk)
            while pending:
                written = os.write(output, pending)
                if written <= 0:
                    fail("LINUX_ARTIFACT_UNREADABLE", f"cannot snapshot {label}")
                pending = pending[written:]
        os.fsync(output)
        after = os.fstat(source)
        if not _same_file_identity(before, after) or copied != before.st_size:
            fail("LINUX_ARTIFACT_CHANGED", f"{label} changed while it was snapshotted")
        snapshot_metadata = os.fstat(output)
        if snapshot_metadata.st_size != before.st_size:
            fail("LINUX_ARTIFACT_CHANGED", f"{label} snapshot size is incomplete")
        return (
            StableFile(
                path=path,
                sha256=digest.hexdigest(),
                size=before.st_size,
                uid=before.st_uid,
                gid=before.st_gid,
                mode=stat.S_IMODE(before.st_mode),
                device=before.st_dev,
                inode=before.st_ino,
                mtime_ns=before.st_mtime_ns,
                ctime_ns=before.st_ctime_ns,
            ),
            snapshot_path,
        )
    except LinuxGateError:
        raise
    except OSError as error:
        fail("LINUX_ARTIFACT_UNREADABLE", f"cannot snapshot {label}: {error}")
    finally:
        if output >= 0:
            os.close(output)
        os.close(source)
        if sys.exc_info()[0] is not None:
            try:
                os.unlink(snapshot_path)
            except FileNotFoundError:
                pass


def verify_source_unchanged(path: Path, original: StableFile, label: str) -> None:
    """Prove that a receipt path still names the source fd that was snapshotted."""
    current = read_stable_file(path, f"{label} source recheck")
    original_identity = (
        original.device,
        original.inode,
        original.size,
        original.uid,
        original.gid,
        original.mode,
        original.mtime_ns,
        original.ctime_ns,
    )
    current_identity = (
        current.device,
        current.inode,
        current.size,
        current.uid,
        current.gid,
        current.mode,
        current.mtime_ns,
        current.ctime_ns,
    )
    if None in original_identity or current_identity != original_identity:
        fail("LINUX_ARTIFACT_CHANGED", f"{label} path changed during release verification")
    if current.sha256 != original.sha256:
        fail("LINUX_ARTIFACT_CHANGED", f"{label} bytes changed during release verification")


def _reject_duplicate_json_keys(pairs: list[tuple[str, Any]]) -> dict[str, Any]:
    value: dict[str, Any] = {}
    for key, item in pairs:
        if key in value:
            fail("LINUX_JSON_DUPLICATE_KEY", f"duplicate JSON key {key!r}")
        value[key] = item
    return value


def decode_json(content: bytes, label: str) -> dict[str, Any]:
    try:
        value = json.loads(content, object_pairs_hook=_reject_duplicate_json_keys)
    except LinuxGateError:
        raise
    except (UnicodeDecodeError, json.JSONDecodeError) as error:
        fail("LINUX_JSON_INVALID", f"{label} is not valid UTF-8 JSON: {error}")
    if not isinstance(value, dict):
        fail("LINUX_JSON_INVALID", f"{label} must contain one JSON object")
    return value


def load_json(path: Path, label: str) -> tuple[dict[str, Any], StableFile]:
    evidence = read_stable_file(
        path,
        label,
        capture_content=True,
        max_bytes=MAX_JSON_BYTES,
    )
    assert evidence.content is not None
    return decode_json(evidence.content, label), evidence


def require_exact_keys(value: dict[str, Any], expected: Iterable[str], label: str) -> None:
    expected_set = set(expected)
    actual = set(value)
    if actual != expected_set:
        fail(
            "LINUX_SCHEMA_INVALID",
            f"{label} keys differ: missing={sorted(expected_set - actual)}, extra={sorted(actual - expected_set)}",
        )


def object_value(value: dict[str, Any], key: str, label: str) -> dict[str, Any]:
    item = value.get(key)
    if not isinstance(item, dict):
        fail("LINUX_SCHEMA_INVALID", f"{label}.{key} must be an object")
    return item


def string_value(value: dict[str, Any], key: str, label: str) -> str:
    item = value.get(key)
    if not isinstance(item, str):
        fail("LINUX_SCHEMA_INVALID", f"{label}.{key} must be a string")
    return item


def integer_value(value: dict[str, Any], key: str, label: str) -> int:
    item = value.get(key)
    if isinstance(item, bool) or not isinstance(item, int):
        fail("LINUX_SCHEMA_INVALID", f"{label}.{key} must be an integer")
    return item


def boolean_value(value: dict[str, Any], key: str, label: str) -> bool:
    item = value.get(key)
    if not isinstance(item, bool):
        fail("LINUX_SCHEMA_INVALID", f"{label}.{key} must be a boolean")
    return item


def parse_mode(value: str, label: str) -> int:
    if not re.fullmatch(r"0[0-7]{3}", value):
        fail("LINUX_RELEASE_POLICY_INVALID", f"{label} must be a four-digit octal mode")
    return int(value, 8)


def normalize_fingerprint(value: str, label: str, *, allow_unconfigured: bool = False) -> str:
    if allow_unconfigured and value == "UNCONFIGURED":
        return value
    if not FINGERPRINT_RE.fullmatch(value):
        fail(
            "LINUX_SIGNER_FINGERPRINT_INVALID",
            f"{label} must be a complete 40- or 64-hex OpenPGP fingerprint",
        )
    normalized = value.upper()
    if set(normalized) == {"0"}:
        fail("LINUX_SIGNER_FINGERPRINT_INVALID", f"{label} cannot be all zeroes")
    return normalized


def validate_policy_sha256(value: Any, label: str) -> str:
    if not isinstance(value, str):
        fail("LINUX_RELEASE_POLICY_INVALID", f"{label} must be a SHA-256 string")
    if not SHA256_RE.fullmatch(value) or set(value.lower()) == {"0"}:
        fail("LINUX_RELEASE_POLICY_INVALID", f"fixed policy must pin {label} as a nonzero SHA-256")
    return value.lower()


def validate_policy(policy: dict[str, Any]) -> None:
    require_exact_keys(
        policy,
        {
            "schemaVersion",
            "configurationState",
            "platform",
            "captureProvider",
            "packageName",
            "capturePackageKinds",
            "packageDependencyContractState",
            "packageDependencies",
            "appImageCaptureDisabled",
            "supportedArchitectures",
            "installedArtifacts",
            "helperPolicy",
            "polkit",
            "packagePayload",
            "packageSignatures",
            "packageScripts",
        },
        "releasePolicy",
    )
    if integer_value(policy, "schemaVersion", "releasePolicy") != POLICY_SCHEMA_VERSION:
        fail("LINUX_RELEASE_POLICY_INVALID", "unsupported release policy schemaVersion")
    state = string_value(policy, "configurationState", "releasePolicy")
    if state not in {"unconfigured", "configured"}:
        fail("LINUX_RELEASE_POLICY_INVALID", "configurationState must be configured or unconfigured")
    if string_value(policy, "platform", "releasePolicy") != PLATFORM:
        fail("LINUX_RELEASE_POLICY_INVALID", "release policy platform must be linux")
    if string_value(policy, "captureProvider", "releasePolicy") != CAPTURE_PROVIDER:
        fail("LINUX_RELEASE_POLICY_INVALID", "release policy provider is unsupported")
    package_name = string_value(policy, "packageName", "releasePolicy")
    if not re.fullmatch(r"[a-z0-9][a-z0-9+.-]{0,127}", package_name):
        fail("LINUX_RELEASE_POLICY_INVALID", "packageName is invalid")

    capture_package_kinds = policy.get("capturePackageKinds")
    if capture_package_kinds != list(CAPTURE_PACKAGE_KINDS):
        fail("LINUX_RELEASE_POLICY_INVALID", "capturePackageKinds must be exactly [deb, rpm]")
    dependency_contract_state = string_value(
        policy,
        "packageDependencyContractState",
        "releasePolicy",
    )
    if dependency_contract_state not in {"unconfigured", "configured"}:
        fail(
            "LINUX_RELEASE_POLICY_INVALID",
            "packageDependencyContractState must be configured or unconfigured",
        )
    if state == "configured" and dependency_contract_state != "configured":
        fail(
            "LINUX_RELEASE_POLICY_INVALID",
            "configured releases require a frozen distro/architecture dependency contract",
        )
    package_dependencies = object_value(policy, "packageDependencies", "releasePolicy")
    require_exact_keys(package_dependencies, PACKAGE_KINDS, "releasePolicy.packageDependencies")
    for kind, expected in PACKAGE_DEPENDENCIES.items():
        if package_dependencies.get(kind) != list(expected):
            fail(
                "LINUX_RELEASE_POLICY_INVALID",
                f"{kind} packageDependencies must be exactly {list(expected)}",
            )
    if not boolean_value(policy, "appImageCaptureDisabled", "releasePolicy"):
        fail("LINUX_RELEASE_POLICY_INVALID", "ordinary AppImage/updater capture must remain disabled")

    architectures = policy.get("supportedArchitectures")
    if not isinstance(architectures, list) or any(not isinstance(item, str) for item in architectures):
        fail("LINUX_RELEASE_POLICY_INVALID", "supportedArchitectures must be a string array")
    if len(architectures) != len(set(architectures)) or not set(architectures) <= SUPPORTED_ARCHITECTURES:
        fail("LINUX_RELEASE_POLICY_INVALID", "supportedArchitectures contains duplicates or unsupported values")

    artifacts = object_value(policy, "installedArtifacts", "releasePolicy")
    require_exact_keys(artifacts, ROLE_NAMES, "releasePolicy.installedArtifacts")
    paths: list[str] = []
    for role in ROLE_NAMES:
        contract = object_value(artifacts, role, "releasePolicy.installedArtifacts")
        expected_keys = {"path", "uid", "gid", "mode"}
        if role == "helper":
            expected_keys.add("requireNoFileCapabilities")
        require_exact_keys(contract, expected_keys, f"releasePolicy.installedArtifacts.{role}")
        path = string_value(contract, "path", f"releasePolicy.installedArtifacts.{role}")
        if not path.startswith("/") or "\x00" in path or ".." in PurePosixPath(path).parts:
            fail("LINUX_RELEASE_POLICY_INVALID", f"{role} path must be a fixed absolute path")
        if integer_value(contract, "uid", f"releasePolicy.installedArtifacts.{role}") != 0:
            fail("LINUX_RELEASE_POLICY_INVALID", f"{role} must be owned by uid 0")
        if integer_value(contract, "gid", f"releasePolicy.installedArtifacts.{role}") != 0:
            fail("LINUX_RELEASE_POLICY_INVALID", f"{role} must be owned by gid 0")
        parse_mode(string_value(contract, "mode", f"releasePolicy.installedArtifacts.{role}"), role)
        if role == "helper" and not boolean_value(contract, "requireNoFileCapabilities", f"releasePolicy.installedArtifacts.{role}"):
            fail("LINUX_RELEASE_POLICY_INVALID", "helper must forbid file capabilities")
        paths.append(path)
    if len(paths) != len(set(paths)):
        fail("LINUX_RELEASE_POLICY_INVALID", "installed artifact paths must be unique")

    helper_policy = object_value(policy, "helperPolicy", "releasePolicy")
    require_exact_keys(helper_policy, {"schemaVersion", "productId", "pinMode"}, "releasePolicy.helperPolicy")
    if integer_value(helper_policy, "schemaVersion", "releasePolicy.helperPolicy") != 1:
        fail("LINUX_RELEASE_POLICY_INVALID", "helper policy schemaVersion must be 1")
    if string_value(helper_policy, "productId", "releasePolicy.helperPolicy") != "com.taomni.app":
        fail("LINUX_RELEASE_POLICY_INVALID", "helper policy productId is invalid")
    if string_value(helper_policy, "pinMode", "releasePolicy.helperPolicy") != "exact_installed_only":
        fail("LINUX_RELEASE_POLICY_INVALID", "helper policy pinMode must be exact_installed_only")

    polkit = object_value(policy, "polkit", "releasePolicy")
    require_exact_keys(
        polkit,
        {"actionId", "execPath", "allowAny", "allowInactive", "allowActive", "retainAuthorization"},
        "releasePolicy.polkit",
    )
    if string_value(polkit, "actionId", "releasePolicy.polkit") != "com.taomni.sockscap.helper":
        fail("LINUX_RELEASE_POLICY_INVALID", "polkit actionId is invalid")
    if string_value(polkit, "execPath", "releasePolicy.polkit") != artifacts["helper"]["path"]:
        fail("LINUX_RELEASE_POLICY_INVALID", "polkit execPath must equal the fixed helper path")
    expected_defaults = {"allowAny": "no", "allowInactive": "no", "allowActive": "auth_admin"}
    for key, expected in expected_defaults.items():
        if string_value(polkit, key, "releasePolicy.polkit") != expected:
            fail("LINUX_RELEASE_POLICY_INVALID", f"polkit {key} must be {expected}")
    if boolean_value(polkit, "retainAuthorization", "releasePolicy.polkit"):
        fail("LINUX_RELEASE_POLICY_INVALID", "polkit retained authorization is forbidden")

    package_payload = object_value(policy, "packagePayload", "releasePolicy")
    require_exact_keys(
        package_payload,
        {"desktopFiles", "iconFiles"},
        "releasePolicy.packagePayload",
    )
    if package_payload.get("desktopFiles") != list(PACKAGE_DESKTOP_FILES):
        fail("LINUX_RELEASE_POLICY_INVALID", "desktopFiles differ from the fixed Taomni package contract")
    if package_payload.get("iconFiles") != list(PACKAGE_ICON_FILES):
        fail("LINUX_RELEASE_POLICY_INVALID", "iconFiles differ from the fixed Taomni package contract")

    signatures = object_value(policy, "packageSignatures", "releasePolicy")
    require_exact_keys(signatures, PACKAGE_KINDS, "releasePolicy.packageSignatures")
    expected_schemes = {"deb": "detached_openpgp", "rpm": "rpm_embedded_openpgp"}
    for kind, scheme in expected_schemes.items():
        signature = object_value(signatures, kind, "releasePolicy.packageSignatures")
        require_exact_keys(signature, {"scheme", "signerFingerprint"}, f"releasePolicy.packageSignatures.{kind}")
        if string_value(signature, "scheme", f"releasePolicy.packageSignatures.{kind}") != scheme:
            fail("LINUX_RELEASE_POLICY_INVALID", f"{kind} signature scheme must be {scheme}")
        fingerprint = string_value(signature, "signerFingerprint", f"releasePolicy.packageSignatures.{kind}")
        normalize_fingerprint(fingerprint, f"releasePolicy.packageSignatures.{kind}", allow_unconfigured=state == "unconfigured")

    package_scripts = object_value(policy, "packageScripts", "releasePolicy")
    require_exact_keys(
        package_scripts,
        {"normalization", "interpreter", "definitions", "mappings"},
        "releasePolicy.packageScripts",
    )
    if string_value(package_scripts, "normalization", "releasePolicy.packageScripts") != PACKAGE_SCRIPT_NORMALIZATION:
        fail("LINUX_RELEASE_POLICY_INVALID", "package script normalization contract is unsupported")
    if string_value(package_scripts, "interpreter", "releasePolicy.packageScripts") != "/bin/sh":
        fail("LINUX_RELEASE_POLICY_INVALID", "package scripts must use /bin/sh")
    definitions = object_value(package_scripts, "definitions", "releasePolicy.packageScripts")
    require_exact_keys(definitions, PACKAGE_SCRIPT_NAMES, "releasePolicy.packageScripts.definitions")
    for logical_name in PACKAGE_SCRIPT_NAMES:
        definition = object_value(definitions, logical_name, "releasePolicy.packageScripts.definitions")
        require_exact_keys(
            definition,
            {"normalizedSha256", "rawSha256"},
            f"releasePolicy.packageScripts.definitions.{logical_name}",
        )
        validate_policy_sha256(
            definition.get("normalizedSha256"),
            f"packageScripts.definitions.{logical_name}.normalizedSha256",
        )
        raw_hashes = object_value(
            definition,
            "rawSha256",
            f"releasePolicy.packageScripts.definitions.{logical_name}",
        )
        require_exact_keys(
            raw_hashes,
            PACKAGE_KINDS,
            f"releasePolicy.packageScripts.definitions.{logical_name}.rawSha256",
        )
        for kind in CAPTURE_PACKAGE_KINDS:
            validate_policy_sha256(
                raw_hashes.get(kind),
                f"packageScripts.definitions.{logical_name}.rawSha256.{kind}",
            )
    mappings = object_value(package_scripts, "mappings", "releasePolicy.packageScripts")
    require_exact_keys(mappings, PACKAGE_KINDS, "releasePolicy.packageScripts.mappings")
    for kind in CAPTURE_PACKAGE_KINDS:
        mapping = object_value(mappings, kind, "releasePolicy.packageScripts.mappings")
        if mapping != PACKAGE_SCRIPT_MAPPINGS[kind]:
            fail("LINUX_RELEASE_POLICY_INVALID", f"{kind} package script mapping differs from the fixed contract")

    if state == "unconfigured":
        if architectures:
            fail("LINUX_RELEASE_POLICY_INVALID", "unconfigured policy must not claim supported architectures")
        if any(signatures[kind]["signerFingerprint"] != "UNCONFIGURED" for kind in PACKAGE_KINDS):
            fail("LINUX_RELEASE_POLICY_INVALID", "unconfigured policy must not pin a partial signing identity")
    else:
        if not architectures:
            fail("LINUX_RELEASE_POLICY_INVALID", "configured policy requires a non-empty architecture set")
        for kind in PACKAGE_KINDS:
            normalize_fingerprint(signatures[kind]["signerFingerprint"], f"releasePolicy.packageSignatures.{kind}")


def validate_safe_relative_path(value: str, label: str, *, allow_empty: bool = False) -> None:
    if allow_empty and value == "":
        return
    path = PurePosixPath(value)
    if not value or path.is_absolute() or ".." in path.parts or "\x00" in value:
        fail("LINUX_MANIFEST_PATH_INVALID", f"{label} must stay inside the manifest directory")


def validate_manifest(manifest: dict[str, Any], policy: dict[str, Any], *, lint: bool) -> None:
    require_exact_keys(
        manifest,
        {
            "schemaVersion",
            "captureReleaseEnabled",
            "gitCommit",
            "buildId",
            "platform",
            "architecture",
            "captureProvider",
            "package",
            "installedArtifacts",
            "packageManifestOutput",
        },
        "manifest",
    )
    if integer_value(manifest, "schemaVersion", "manifest") != MANIFEST_SCHEMA_VERSION:
        fail("LINUX_MANIFEST_INVALID", "unsupported manifest schemaVersion")
    boolean_value(manifest, "captureReleaseEnabled", "manifest")
    string_value(manifest, "gitCommit", "manifest")
    string_value(manifest, "buildId", "manifest")
    if string_value(manifest, "platform", "manifest") != PLATFORM:
        fail("LINUX_MANIFEST_INVALID", "manifest platform must be linux")
    architecture = string_value(manifest, "architecture", "manifest")
    if architecture not in SUPPORTED_ARCHITECTURES:
        fail("LINUX_MANIFEST_INVALID", "manifest architecture is unsupported")
    if string_value(manifest, "captureProvider", "manifest") != policy["captureProvider"]:
        fail("LINUX_RELEASE_POLICY_MISMATCH", "manifest provider differs from fixed policy")
    if policy["configurationState"] == "configured" and architecture not in policy["supportedArchitectures"]:
        fail("LINUX_RELEASE_POLICY_MISMATCH", "manifest architecture is not in the fixed support set")

    installed = object_value(manifest, "installedArtifacts", "manifest")
    require_exact_keys(installed, ROLE_NAMES, "manifest.installedArtifacts")
    for role in ROLE_NAMES:
        if string_value(installed, role, "manifest.installedArtifacts") != policy["installedArtifacts"][role]["path"]:
            fail("LINUX_RELEASE_POLICY_MISMATCH", f"manifest {role} path differs from fixed policy")

    package = object_value(manifest, "package", "manifest")
    require_exact_keys(package, {"kind", "path", "sha256", "signature"}, "manifest.package")
    kind = string_value(package, "kind", "manifest.package")
    if kind not in PACKAGE_KINDS:
        fail(
            "LINUX_PACKAGE_KIND_INVALID",
            "capture package kind must be deb or rpm; AppImage/updater capture is disabled",
        )
    if kind not in policy["capturePackageKinds"] or not policy["appImageCaptureDisabled"]:
        fail("LINUX_RELEASE_POLICY_MISMATCH", "manifest violates the fixed capture packaging contract")
    validate_safe_relative_path(string_value(package, "path", "manifest.package"), "package.path")
    package_sha256 = string_value(package, "sha256", "manifest.package")
    if not lint and not SHA256_RE.fullmatch(package_sha256):
        fail("LINUX_MANIFEST_INVALID", "package.sha256 must be a SHA-256 in release mode")
    if lint and package_sha256 and not SHA256_RE.fullmatch(package_sha256):
        fail("LINUX_MANIFEST_INVALID", "non-empty package.sha256 is invalid")

    signature = object_value(package, "signature", "manifest.package")
    require_exact_keys(
        signature,
        {"scheme", "path", "sha256", "publicKeyPath", "publicKeySha256"},
        "manifest.package.signature",
    )
    expected_scheme = policy["packageSignatures"][kind]["scheme"]
    if string_value(signature, "scheme", "manifest.package.signature") != expected_scheme:
        fail("LINUX_RELEASE_POLICY_MISMATCH", "signature scheme differs from fixed policy")
    signature_path = string_value(signature, "path", "manifest.package.signature")
    signature_sha256 = string_value(signature, "sha256", "manifest.package.signature")
    if kind == "deb":
        validate_safe_relative_path(signature_path, "package.signature.path")
        if not lint and not SHA256_RE.fullmatch(signature_sha256):
            fail("LINUX_MANIFEST_INVALID", "detached signature SHA-256 is required")
        if lint and signature_sha256 and not SHA256_RE.fullmatch(signature_sha256):
            fail("LINUX_MANIFEST_INVALID", "detached signature SHA-256 is invalid")
    elif signature_path or signature_sha256:
        fail("LINUX_MANIFEST_INVALID", "RPM embedded signatures must not declare a detached signature")
    public_key_path = string_value(signature, "publicKeyPath", "manifest.package.signature")
    validate_safe_relative_path(public_key_path, "package.signature.publicKeyPath")
    public_key_sha256 = string_value(signature, "publicKeySha256", "manifest.package.signature")
    if not lint and not SHA256_RE.fullmatch(public_key_sha256):
        fail("LINUX_MANIFEST_INVALID", "signing public key SHA-256 is required")
    if lint and public_key_sha256 and not SHA256_RE.fullmatch(public_key_sha256):
        fail("LINUX_MANIFEST_INVALID", "signing public key SHA-256 is invalid")
    validate_safe_relative_path(string_value(manifest, "packageManifestOutput", "manifest"), "packageManifestOutput")


def resolve_manifest_file(manifest_directory: Path, value: str, label: str) -> Path:
    validate_safe_relative_path(value, label)
    return absolute_path(manifest_directory / PurePosixPath(value))


def verify_expected_hash(evidence: StableFile, expected: str, label: str) -> None:
    if evidence.sha256.lower() != expected.lower():
        fail("LINUX_ARTIFACT_HASH_MISMATCH", f"{label} SHA-256 differs from the manifest")


def read_file_capabilities(descriptor: int) -> bytes:
    try:
        return os.getxattr(descriptor, "security.capability")
    except OSError as error:
        no_attribute = {
            getattr(errno, "ENODATA", -1),
            getattr(errno, "ENOATTR", -1),
            errno.ENOTSUP,
        }
        if error.errno in no_attribute:
            return b""
        fail("LINUX_HELPER_CAPABILITY_CHECK_FAILED", f"cannot read helper file capabilities: {error}")


def inspect_installed_artifact(path: Path, role: str, contract: dict[str, Any]) -> StableFile:
    capture_content = role in {"helperPolicy", "polkitAction"}
    maximum = MAX_POLICY_BYTES if role == "helperPolicy" else MAX_POLKIT_BYTES if role == "polkitAction" else None
    evidence = read_stable_file(
        path,
        f"installed {role}",
        capture_content=capture_content,
        capture_file_capabilities=role == "helper",
        max_bytes=maximum,
    )
    expected_mode = parse_mode(contract["mode"], f"installedArtifacts.{role}.mode")
    if evidence.uid != contract["uid"] or evidence.gid != contract["gid"]:
        fail("LINUX_ARTIFACT_OWNER_INVALID", f"installed {role} must be root:root")
    if evidence.mode != expected_mode:
        fail(
            "LINUX_ARTIFACT_MODE_INVALID",
            f"installed {role} mode is {evidence.mode:04o}, expected {expected_mode:04o}",
        )
    if role == "helper":
        if evidence.mode & (stat.S_ISUID | stat.S_ISGID):
            fail("LINUX_HELPER_PRIVILEGE_BITS_INVALID", "helper must not be setuid or setgid")
        if contract["requireNoFileCapabilities"]:
            if evidence.file_capabilities is None:
                fail(
                    "LINUX_HELPER_CAPABILITY_CHECK_FAILED",
                    "helper capability evidence was not captured from its stable descriptor",
                )
            if evidence.file_capabilities:
                fail("LINUX_HELPER_FILE_CAPABILITIES_INVALID", "helper must not carry file capabilities")
    return evidence


def validate_digest_list(value: Any, label: str) -> list[str]:
    if not isinstance(value, list) or not 1 <= len(value) <= 16 or any(not isinstance(item, str) for item in value):
        fail("LINUX_HELPER_POLICY_INVALID", f"{label} must contain 1-16 SHA-256 strings")
    normalized = [item.lower() for item in value]
    if any(not SHA256_RE.fullmatch(item) for item in normalized) or len(normalized) != len(set(normalized)):
        fail("LINUX_HELPER_POLICY_INVALID", f"{label} contains invalid or duplicate SHA-256 pins")
    return normalized


def verify_helper_policy(content: bytes, contract: dict[str, Any], app_sha256: str, helper_sha256: str) -> None:
    policy = decode_json(content, "installed helper policy")
    require_exact_keys(
        policy,
        {"schemaVersion", "productId", "allowedCallerSha256", "allowedHelperSha256", "allowedRuntimeSha256"},
        "installedHelperPolicy",
    )
    if integer_value(policy, "schemaVersion", "installedHelperPolicy") != contract["schemaVersion"]:
        fail("LINUX_HELPER_POLICY_INVALID", "installed helper policy schemaVersion is wrong")
    if string_value(policy, "productId", "installedHelperPolicy") != contract["productId"]:
        fail("LINUX_HELPER_POLICY_INVALID", "installed helper policy productId is wrong")
    callers = validate_digest_list(policy["allowedCallerSha256"], "allowedCallerSha256")
    helpers = validate_digest_list(policy["allowedHelperSha256"], "allowedHelperSha256")
    runtimes = validate_digest_list(policy["allowedRuntimeSha256"], "allowedRuntimeSha256")
    if contract["pinMode"] != "exact_installed_only":
        fail("LINUX_HELPER_POLICY_INVALID", "unsupported helper policy pin mode")
    if callers != [app_sha256.lower()] or runtimes != [app_sha256.lower()] or helpers != [helper_sha256.lower()]:
        fail("LINUX_HELPER_POLICY_PIN_MISMATCH", "helper policy pins do not exactly match installed app/helper")


def verify_polkit_action(content: bytes, contract: dict[str, Any]) -> None:
    if b"<!ENTITY" in content.upper():
        fail("LINUX_POLKIT_INVALID", "polkit action must not declare XML entities")
    try:
        root = ElementTree.fromstring(content)
    except ElementTree.ParseError as error:
        fail("LINUX_POLKIT_INVALID", f"polkit action XML is invalid: {error}")
    if root.tag != "policyconfig":
        fail("LINUX_POLKIT_INVALID", "polkit root element must be policyconfig")
    actions = root.findall("action")
    if len(actions) != 1 or actions[0].attrib != {"id": contract["actionId"]}:
        fail("LINUX_POLKIT_INVALID", "polkit file must contain exactly the fixed action")
    action = actions[0]
    defaults_nodes = action.findall("defaults")
    if len(defaults_nodes) != 1:
        fail("LINUX_POLKIT_INVALID", "polkit action must contain exactly one defaults block")
    defaults = defaults_nodes[0]
    expected_defaults = {
        "allow_any": contract["allowAny"],
        "allow_inactive": contract["allowInactive"],
        "allow_active": contract["allowActive"],
    }
    for tag, expected in expected_defaults.items():
        nodes = defaults.findall(tag)
        if len(nodes) != 1 or (nodes[0].text or "").strip() != expected:
            fail("LINUX_POLKIT_INVALID", f"polkit {tag} must be exactly {expected}")
    if set(child.tag for child in defaults) != set(expected_defaults):
        fail("LINUX_POLKIT_INVALID", "polkit defaults contains an unsupported authorization mode")
    annotations = action.findall("annotate")
    expected_annotation = {
        "key": "org.freedesktop.policykit.exec.path",
    }
    if (
        len(annotations) != 1
        or annotations[0].attrib != expected_annotation
        or (annotations[0].text or "").strip() != contract["execPath"]
    ):
        fail("LINUX_POLKIT_INVALID", "polkit action must annotate only the fixed helper path")
    if contract["retainAuthorization"] or "_keep" in contract["allowActive"]:
        fail("LINUX_POLKIT_INVALID", "retained polkit authorization is forbidden")


def resolve_tool(name: str) -> str:
    for directory in FIXED_TOOL_DIRECTORIES:
        candidate = directory / name
        try:
            metadata = os.stat(candidate, follow_symlinks=True)
        except OSError:
            continue
        if stat.S_ISREG(metadata.st_mode) and os.access(candidate, os.X_OK):
            return os.fspath(candidate)
    fail("LINUX_TOOL_MISSING", f"required tool {name!r} is unavailable in the system allowlist")


def hermetic_tool_environment() -> dict[str, str]:
    # Never inherit loader hooks, user RPM macros/plugins, GnuPG homes, Python
    # hooks, or package-manager configuration from the invoking account.
    return {
        "HOME": "/nonexistent",
        "LANG": "C",
        "LC_ALL": "C",
        "PATH": ":".join(os.fspath(path) for path in FIXED_TOOL_DIRECTORIES),
        "TEMP": "/tmp",
        "TMP": "/tmp",
        "TMPDIR": "/tmp",
        "TZ": "UTC",
        "XDG_CONFIG_HOME": "/nonexistent",
        "XDG_DATA_HOME": "/nonexistent",
    }


def run_tool(name: str, arguments: list[str], *, check: bool = True) -> subprocess.CompletedProcess[str]:
    command = [resolve_tool(name), *arguments]
    result = subprocess.run(
        command,
        text=True,
        capture_output=True,
        env=hermetic_tool_environment(),
        check=False,
    )
    if check and result.returncode != 0:
        diagnostic = (result.stderr or result.stdout).strip()[:2000]
        fail("LINUX_TOOL_FAILED", f"{name} failed: {diagnostic}")
    return result


def run_tool_bytes(name: str, arguments: list[str], *, check: bool = True) -> subprocess.CompletedProcess[bytes]:
    command = [resolve_tool(name), *arguments]
    result = subprocess.run(
        command,
        capture_output=True,
        env=hermetic_tool_environment(),
        check=False,
    )
    if check and result.returncode != 0:
        diagnostic = (result.stderr or result.stdout).decode("utf-8", "replace").strip()[:2000]
        fail("LINUX_TOOL_FAILED", f"{name} failed: {diagnostic}")
    return result


def openpgp_primary_fingerprint(public_key: Path) -> str:
    with tempfile.TemporaryDirectory(
        prefix="taomni-linux-gate-gpg-", dir="/tmp"
    ) as directory:
        os.chmod(directory, 0o700)
        result = run_tool(
            "gpg",
            [
                "--batch",
                "--no-options",
                "--homedir",
                directory,
                "--with-colons",
                "--import-options",
                "show-only",
                "--dry-run",
                "--import",
                os.fspath(public_key),
            ],
        )
    fingerprints: list[str] = []
    awaiting_primary = False
    for line in result.stdout.splitlines():
        fields = line.split(":")
        record = fields[0] if fields else ""
        if record == "pub":
            awaiting_primary = True
        elif record == "sub":
            awaiting_primary = False
        elif record == "fpr" and awaiting_primary and len(fields) > 9:
            fingerprints.append(normalize_fingerprint(fields[9], "public key fingerprint"))
            awaiting_primary = False
    if len(fingerprints) != 1:
        fail("LINUX_SIGNING_KEY_INVALID", "public key file must contain exactly one primary OpenPGP key")
    return fingerprints[0]


def verify_deb_signature(package: Path, signature: Path, public_key: Path, expected_fingerprint: str) -> str:
    with tempfile.TemporaryDirectory(
        prefix="taomni-linux-gate-gpg-", dir="/tmp"
    ) as directory:
        os.chmod(directory, 0o700)
        run_tool(
            "gpg",
            ["--batch", "--no-options", "--homedir", directory, "--import", os.fspath(public_key)],
        )
        # GnuPG 2.4 imports into pubring.kbx, while gpgv's legacy default is
        # trustedkeys.kbx. Export the one pinned key into an explicit packet
        # keyring so verification never depends on either default filename.
        keyring = Path(directory) / "release-signing-key.gpg"
        run_tool(
            "gpg",
            [
                "--batch",
                "--no-options",
                "--homedir",
                directory,
                "--output",
                os.fspath(keyring),
                "--export-options",
                "export-minimal",
                "--export",
                expected_fingerprint,
            ],
        )
        result = run_tool(
            "gpgv",
            [
                "--homedir",
                directory,
                "--keyring",
                os.fspath(keyring),
                "--status-fd",
                "1",
                os.fspath(signature),
                os.fspath(package),
            ],
        )
    valid_lines = [line for line in result.stdout.splitlines() if line.startswith("[GNUPG:] VALIDSIG ")]
    if len(valid_lines) != 1:
        fail("LINUX_PACKAGE_SIGNATURE_INVALID", "detached signature did not emit one VALIDSIG proof")
    fingerprints = {
        token.upper()
        for token in valid_lines[0].split()[2:]
        if FINGERPRINT_RE.fullmatch(token)
    }
    if expected_fingerprint.upper() not in fingerprints:
        fail("LINUX_PACKAGE_SIGNER_MISMATCH", "detached signature signer differs from fixed policy")
    return expected_fingerprint.upper()


def verify_rpm_signature(package: Path, public_key: Path, expected_fingerprint: str) -> str:
    with tempfile.TemporaryDirectory(
        prefix="taomni-linux-gate-rpm-", dir="/tmp"
    ) as directory:
        database = Path(directory) / "rpmdb"
        database.mkdir(mode=0o700)
        run_tool("rpm", ["--noplugins", "--dbpath", os.fspath(database), "--initdb"])
        run_tool(
            "rpmkeys",
            ["--noplugins", "--dbpath", os.fspath(database), "--import", os.fspath(public_key)],
        )
        result = run_tool(
            "rpmkeys",
            [
                "--noplugins",
                "--dbpath",
                os.fspath(database),
                "--checksig",
                "--verbose",
                os.fspath(package),
            ],
        )
    output = f"{result.stdout}\n{result.stderr}".lower()
    if re.search(r"\b(?:not\s+ok|notsigned|no\s+key|nokey)\b", output):
        fail("LINUX_PACKAGE_SIGNATURE_INVALID", "RPM signature output reports an untrusted package")
    if not (
        re.search(r"signature[^\n]*:\s*ok\b", output)
        or re.search(r"\bsignatures\s+ok\b", output)
    ):
        fail("LINUX_PACKAGE_SIGNATURE_INVALID", "RPM has no verified embedded OpenPGP signature")
    return expected_fingerprint.upper()


def normalize_package_path(value: str) -> str:
    path = PurePosixPath(value)
    parts = [part for part in path.parts if part not in {"/", ".", ""}]
    if not parts or ".." in parts or "\x00" in value:
        fail("LINUX_PACKAGE_CONTENT_INVALID", f"unsafe package member path {value!r}")
    return "/" + "/".join(parts)


def parse_deb_dependency_atom(value: str) -> str:
    atom = value.strip()
    while re.search(r"\s+<[^<>]+>\s*$", atom):
        atom = re.sub(r"\s+<[^<>]+>\s*$", "", atom)
    atom = re.sub(r"\s+\[[^\[\]]+\]\s*$", "", atom)
    atom = re.sub(r"\s+\([^()]+\)\s*$", "", atom)
    match = re.fullmatch(r"([a-z0-9][a-z0-9+.-]*)(?::[A-Za-z0-9][A-Za-z0-9-]*)?", atom)
    if match is None:
        fail("LINUX_PACKAGE_DEPENDENCY_INVALID", f"malformed DEB dependency atom {value!r}")
    return match.group(1)


def parse_deb_dependencies(value: str) -> dict[str, list[str]]:
    if "\x00" in value or len(value.encode("utf-8")) > MAX_POLICY_BYTES:
        fail("LINUX_PACKAGE_DEPENDENCY_INVALID", "DEB dependency metadata is unsafe or too large")
    requirements = [item.strip() for item in value.replace("\n", " ").split(",") if item.strip()]
    direct_packages: list[str] = []
    for requirement in requirements:
        alternatives = [item.strip() for item in requirement.split("|")]
        if any(not item for item in alternatives):
            fail("LINUX_PACKAGE_DEPENDENCY_INVALID", f"malformed DEB dependency {requirement!r}")
        names = [parse_deb_dependency_atom(item) for item in alternatives]
        if len(names) == 1:
            direct_packages.append(names[0])
    return {
        "requirements": requirements,
        "directPackages": sorted(set(direct_packages)),
    }


def parse_rpm_dependencies(value: str) -> dict[str, list[str]]:
    if "\x00" in value or len(value.encode("utf-8")) > MAX_POLICY_BYTES:
        fail("LINUX_PACKAGE_DEPENDENCY_INVALID", "RPM dependency metadata is unsafe or too large")
    requirements = [line.strip() for line in value.splitlines() if line.strip()]
    direct_packages: list[str] = []
    for requirement in requirements:
        if any(ord(character) < 0x20 and character != "\t" for character in requirement):
            fail("LINUX_PACKAGE_DEPENDENCY_INVALID", "RPM dependency metadata contains control bytes")
        name = requirement.split(None, 1)[0]
        if not name or len(name) > 512:
            fail("LINUX_PACKAGE_DEPENDENCY_INVALID", f"malformed RPM dependency {requirement!r}")
        direct_packages.append(name)
    return {
        "requirements": requirements,
        "directPackages": sorted(set(direct_packages)),
    }


def package_path_is_archive_root(value: str) -> bool:
    return not [part for part in PurePosixPath(value).parts if part not in {"/", ".", ""}]


def tar_entry_type(member: tarfile.TarInfo) -> str:
    if member.isfile():
        return "file"
    if member.isdir():
        return "directory"
    if member.issym():
        return "symlink"
    if member.islnk():
        return "hardlink"
    if member.ischr():
        return "char_device"
    if member.isblk():
        return "block_device"
    if member.isfifo():
        return "fifo"
    return "other"


def normalize_package_script(content: bytes, label: str) -> bytes:
    if not content or len(content) > MAX_PACKAGE_SCRIPT_BYTES:
        fail("LINUX_PACKAGE_SCRIPT_INVALID", f"{label} must be a non-empty script of at most 1 MiB")
    try:
        text = content.decode("utf-8")
    except UnicodeDecodeError as error:
        fail("LINUX_PACKAGE_SCRIPT_INVALID", f"{label} is not UTF-8: {error}")
    if text.startswith("\ufeff") or "\x00" in text:
        fail("LINUX_PACKAGE_SCRIPT_INVALID", f"{label} contains a BOM or NUL byte")
    normalized = text.replace("\r\n", "\n").replace("\r", "\n").rstrip("\n") + "\n"
    return normalized.encode("utf-8")


def package_script_evidence(content: bytes, label: str, interpreter: str) -> dict[str, Any]:
    normalized = normalize_package_script(content, label)
    if normalized.split(b"\n", 1)[0] != f"#!{interpreter}".encode("utf-8"):
        fail("LINUX_PACKAGE_SCRIPT_INVALID", f"{label} must start with #!{interpreter}")
    return {
        "rawSha256": hashlib.sha256(content).hexdigest(),
        "normalizedSha256": hashlib.sha256(normalized).hexdigest(),
        "size": len(content),
        "interpreter": interpreter,
    }


def inspect_deb_control_scripts(package: Path) -> dict[str, dict[str, Any]]:
    tool = resolve_tool("dpkg-deb")
    required_phases = set(PACKAGE_SCRIPT_MAPPINGS["deb"])
    scripts: dict[str, dict[str, Any]] = {}
    seen: set[str] = set()
    with tempfile.TemporaryFile() as diagnostics:
        process = subprocess.Popen(
            [tool, "--ctrl-tarfile", os.fspath(package)],
            stdout=subprocess.PIPE,
            stderr=diagnostics,
            env=hermetic_tool_environment(),
        )
        assert process.stdout is not None
        try:
            with tarfile.open(fileobj=process.stdout, mode="r|*") as archive:
                for member in archive:
                    if package_path_is_archive_root(member.name):
                        continue
                    path = normalize_package_path(member.name)
                    if path in seen:
                        fail("LINUX_PACKAGE_SCRIPT_INVALID", f"duplicate DEB control member {path}")
                    seen.add(path)
                    name = path.removeprefix("/")
                    if "/" in name:
                        fail("LINUX_PACKAGE_SCRIPT_INVALID", f"nested DEB control member is forbidden: {path}")
                    if name not in required_phases:
                        if name not in DEB_ALLOWED_CONTROL_MEMBERS:
                            fail("LINUX_PACKAGE_SCRIPT_INVALID", f"unpinned DEB control member {path}")
                        if (
                            not member.isfile()
                            or member.mode & (0o111 | stat.S_ISUID | stat.S_ISGID | stat.S_IWGRP | stat.S_IWOTH)
                            or member.uid != 0
                            or member.gid != 0
                            or member.size <= 0
                            or member.size > MAX_PACKAGE_SCRIPT_BYTES
                        ):
                            fail("LINUX_PACKAGE_SCRIPT_INVALID", f"unsafe DEB control metadata member {path}")
                        continue
                    if (
                        not member.isfile()
                        or not member.mode & 0o111
                        or member.mode
                        & (
                            stat.S_ISUID
                            | stat.S_ISGID
                            | stat.S_IWGRP
                            | stat.S_IWOTH
                        )
                        or member.uid != 0
                        or member.gid != 0
                    ):
                        fail("LINUX_PACKAGE_SCRIPT_INVALID", f"DEB {name} must be an executable regular script")
                    if member.size <= 0 or member.size > MAX_PACKAGE_SCRIPT_BYTES:
                        fail("LINUX_PACKAGE_SCRIPT_INVALID", f"DEB {name} has an invalid size")
                    source = archive.extractfile(member)
                    if source is None:
                        fail("LINUX_PACKAGE_SCRIPT_INVALID", f"cannot read DEB {name}")
                    content = source.read(MAX_PACKAGE_SCRIPT_BYTES + 1)
                    if len(content) != member.size:
                        fail("LINUX_PACKAGE_SCRIPT_INVALID", f"DEB {name} was not read completely")
                    scripts[name] = package_script_evidence(content, f"DEB {name}", "/bin/sh")
        except LinuxGateError:
            process.kill()
            process.wait()
            raise
        except (tarfile.TarError, OSError) as error:
            process.kill()
            process.wait()
            fail("LINUX_PACKAGE_SCRIPT_INVALID", f"cannot inspect DEB control archive: {error}")
        finally:
            process.stdout.close()
        return_code = process.wait()
        if return_code != 0:
            diagnostics.seek(0)
            detail = diagnostics.read(2000).decode("utf-8", "replace")
            fail("LINUX_PACKAGE_SCRIPT_INVALID", f"dpkg-deb control extraction failed: {detail}")
    if set(scripts) != required_phases:
        fail(
            "LINUX_PACKAGE_SCRIPT_INVALID",
            f"DEB maintainer scripts differ: missing={sorted(required_phases - set(scripts))}",
        )
    if "/control" not in seen:
        fail("LINUX_PACKAGE_SCRIPT_INVALID", "DEB control archive omits the control member")
    return scripts


def inspect_deb_package(package: Path, expected_name: str, expected_architecture: str) -> dict[str, Any]:
    package_name = run_tool("dpkg-deb", ["-f", os.fspath(package), "Package"]).stdout.strip()
    version = run_tool("dpkg-deb", ["-f", os.fspath(package), "Version"]).stdout.strip()
    deb_arch = run_tool("dpkg-deb", ["-f", os.fspath(package), "Architecture"]).stdout.strip()
    dependency_metadata = run_tool("dpkg-deb", ["-f", os.fspath(package), "Depends"]).stdout.strip()
    for field in DEB_FORBIDDEN_RELATIONSHIP_FIELDS:
        value = run_tool("dpkg-deb", ["-f", os.fspath(package), field]).stdout.strip()
        if value:
            fail(
                "LINUX_PACKAGE_SEMANTICS_INVALID",
                f"DEB control field {field} is forbidden by the fixed install contract",
            )
    for field in DEB_BOOLEAN_OR_DEFAULT_NO_FIELDS:
        value = run_tool("dpkg-deb", ["-f", os.fspath(package), field]).stdout.strip()
        if value not in {"", "no"}:
            fail(
                "LINUX_PACKAGE_SEMANTICS_INVALID",
                f"DEB control field {field} changes fixed package-manager semantics",
            )
    architecture = {"amd64": "x86_64", "arm64": "aarch64"}.get(deb_arch, deb_arch)
    if package_name != expected_name or architecture != expected_architecture or not version:
        fail("LINUX_PACKAGE_IDENTITY_INVALID", "DEB name, version, or architecture differs from the release candidate")

    tool = resolve_tool("dpkg-deb")
    entries: list[dict[str, Any]] = []
    seen: set[str] = set()
    with tempfile.TemporaryFile() as diagnostics:
        process = subprocess.Popen(
            [tool, "--fsys-tarfile", os.fspath(package)],
            stdout=subprocess.PIPE,
            stderr=diagnostics,
            env=hermetic_tool_environment(),
        )
        assert process.stdout is not None
        try:
            with tarfile.open(fileobj=process.stdout, mode="r|*") as archive:
                for member in archive:
                    # Canonical Debian data archives commonly start with an
                    # explicit `./` directory entry. It has no install path.
                    if package_path_is_archive_root(member.name):
                        continue
                    path = normalize_package_path(member.name)
                    if path in seen:
                        fail("LINUX_PACKAGE_CONTENT_INVALID", f"duplicate DEB payload path {path}")
                    seen.add(path)
                    entry_type = tar_entry_type(member)
                    digest = ""
                    if entry_type == "file":
                        source = archive.extractfile(member)
                        if source is None:
                            fail("LINUX_PACKAGE_CONTENT_INVALID", f"cannot read DEB payload {path}")
                        hasher = hashlib.sha256()
                        for chunk in iter(lambda: source.read(CHUNK_BYTES), b""):
                            hasher.update(chunk)
                        digest = hasher.hexdigest()
                    entries.append(
                        {
                            "path": path,
                            "type": entry_type,
                            "mode": f"{member.mode & 0o7777:04o}",
                            "owner": str(member.uid),
                            "group": str(member.gid),
                            "size": member.size,
                            "sha256": digest,
                            "linkTarget": member.linkname if entry_type in {"symlink", "hardlink"} else "",
                        }
                    )
        except (tarfile.TarError, OSError) as error:
            process.kill()
            process.wait()
            fail("LINUX_PACKAGE_CONTENT_INVALID", f"cannot inspect DEB payload: {error}")
        finally:
            process.stdout.close()
        return_code = process.wait()
        if return_code != 0:
            diagnostics.seek(0)
            detail = diagnostics.read(2000).decode("utf-8", "replace")
            fail("LINUX_PACKAGE_CONTENT_INVALID", f"dpkg-deb payload extraction failed: {detail}")
    entries.sort(key=lambda item: item["path"])
    scripts = inspect_deb_control_scripts(package)
    return {
        "packageName": package_name,
        "packageVersion": version,
        "architecture": architecture,
        "dependencies": parse_deb_dependencies(dependency_metadata),
        "entries": entries,
        "scripts": scripts,
    }


def rpm_file_type(mode: int) -> str:
    if stat.S_ISREG(mode):
        return "file"
    if stat.S_ISDIR(mode):
        return "directory"
    if stat.S_ISLNK(mode):
        return "symlink"
    if stat.S_ISCHR(mode):
        return "char_device"
    if stat.S_ISBLK(mode):
        return "block_device"
    if stat.S_ISFIFO(mode):
        return "fifo"
    return "other"


def rpm_query_tag(package: Path, tag: str) -> bytes:
    return run_tool_bytes(
        "rpm",
        ["--noplugins", "-qp", "--qf", f"%{{{tag}}}", os.fspath(package)],
    ).stdout


def rpm_tag_is_absent(value: bytes) -> bool:
    return value.strip() in {b"", b"(none)"}


def inspect_rpm_scripts(package: Path) -> dict[str, dict[str, Any]]:
    scripts: dict[str, dict[str, Any]] = {}
    for phase, (body_tag, interpreter_tag) in RPM_SCRIPT_QUERY_TAGS.items():
        content = rpm_query_tag(package, body_tag)
        if rpm_tag_is_absent(content):
            fail("LINUX_PACKAGE_SCRIPT_INVALID", f"RPM %{phase} scriptlet is missing")
        interpreter_bytes = rpm_query_tag(package, interpreter_tag)
        try:
            interpreter = interpreter_bytes.decode("utf-8").strip()
        except UnicodeDecodeError as error:
            fail("LINUX_PACKAGE_SCRIPT_INVALID", f"RPM %{phase} interpreter is not UTF-8: {error}")
        if interpreter != "/bin/sh":
            fail("LINUX_PACKAGE_SCRIPT_INVALID", f"RPM %{phase} interpreter must be /bin/sh")
        scripts[phase] = package_script_evidence(content, f"RPM %{phase}", interpreter)

    # Any additional transaction, verify, or trigger script would execute
    # code that is not represented by the fixed three-script policy.
    for tag in RPM_FORBIDDEN_SCRIPT_TAGS:
        if not rpm_tag_is_absent(rpm_query_tag(package, tag)):
            fail("LINUX_PACKAGE_SCRIPT_INVALID", f"RPM contains unpinned scriptlet tag {tag}")
    for tag in RPM_FORBIDDEN_PRIMARY_SCRIPT_FLAGS:
        if not rpm_tag_is_absent(rpm_query_tag(package, tag)):
            fail("LINUX_PACKAGE_SCRIPT_INVALID", f"RPM contains unsupported scriptlet flags {tag}")
    return scripts


def inspect_rpm_semantics(
    package: Path,
    package_name: str,
    version: str,
    architecture: str,
) -> None:
    for tag in RPM_FORBIDDEN_SEMANTIC_TAGS:
        if not rpm_tag_is_absent(rpm_query_tag(package, tag)):
            fail(
                "LINUX_PACKAGE_SEMANTICS_INVALID",
                f"RPM contains forbidden package-manager metadata tag {tag}",
            )

    provides_output = run_tool(
        "rpm",
        ["--noplugins", "-qp", "--provides", os.fspath(package)],
    ).stdout
    provides = {line.strip() for line in provides_output.splitlines() if line.strip()}
    base_provide = f"{package_name} = {version}"
    architecture_suffix = {"x86_64": "x86-64", "aarch64": "aarch-64"}.get(architecture)
    allowed_provides = {base_provide}
    if architecture_suffix is not None:
        allowed_provides.add(f"{package_name}({architecture_suffix}) = {version}")
    if base_provide not in provides or not provides <= allowed_provides:
        fail(
            "LINUX_PACKAGE_SEMANTICS_INVALID",
            "RPM Provides metadata differs from the fixed package self-identity",
        )


def inspect_rpm_package(package: Path, expected_name: str, expected_architecture: str) -> dict[str, Any]:
    identity = run_tool(
        "rpm",
        [
            "--noplugins",
            "-qp",
            "--qf",
            "%{NAME}\n%{VERSION}-%{RELEASE}\n%{ARCH}\n%{FILEDIGESTALGO}\n",
            os.fspath(package),
        ],
    ).stdout.splitlines()
    if len(identity) != 4:
        fail("LINUX_PACKAGE_IDENTITY_INVALID", "RPM identity query is incomplete")
    package_name, version, architecture, digest_algorithm = identity
    if package_name != expected_name or architecture != expected_architecture or not version:
        fail("LINUX_PACKAGE_IDENTITY_INVALID", "RPM name, version, or architecture differs from the release candidate")
    if digest_algorithm != "8":
        fail("LINUX_PACKAGE_CONTENT_INVALID", "RPM file digests must use SHA-256")
    dependency_metadata = run_tool(
        "rpm", ["--noplugins", "-qp", "--requires", os.fspath(package)]
    ).stdout
    query_format = (
        "[%{FILENAMES}\t%{FILEMODES:octal}\t%{FILEUSERNAME}\t%{FILEGROUPNAME}\t"
        "%{FILESIZES}\t%{FILEDIGESTS}\t%{FILELINKTOS}\t%{FILEINODES}\t%{FILEDEVICES}\t"
        "%{FILECAPS}\t%{FILEFLAGS}\n]"
    )
    output = run_tool(
        "rpm", ["--noplugins", "-qp", "--qf", query_format, os.fspath(package)]
    ).stdout
    entries: list[dict[str, Any]] = []
    seen: set[str] = set()
    hardlink_identities: dict[tuple[int, int], str] = {}
    for line in output.splitlines():
        fields = line.split("\t")
        if len(fields) != 11:
            fail("LINUX_PACKAGE_CONTENT_INVALID", "RPM file metadata query is malformed")
        (
            filename,
            mode_text,
            owner,
            group,
            size_text,
            digest,
            link_target,
            inode_text,
            device_text,
            file_capabilities,
            file_flags_text,
        ) = fields
        path = normalize_package_path(filename)
        if path in seen:
            fail("LINUX_PACKAGE_CONTENT_INVALID", f"duplicate RPM payload path {path}")
        seen.add(path)
        try:
            complete_mode = int(mode_text, 8)
            size = int(size_text)
            inode = int(inode_text)
            device = int(device_text)
            file_flags = int(file_flags_text, 10)
        except ValueError:
            fail("LINUX_PACKAGE_CONTENT_INVALID", f"RPM metadata is invalid for {path}")
        if not rpm_tag_is_absent(file_capabilities.encode("utf-8")):
            fail("LINUX_PACKAGE_CONTENT_INVALID", f"RPM payload {path} carries file capabilities")
        if file_flags != 0:
            fail(
                "LINUX_PACKAGE_SEMANTICS_INVALID",
                f"RPM payload {path} carries package-manager file flags {file_flags}",
            )
        entry_type = rpm_file_type(complete_mode)
        if entry_type == "file" and not SHA256_RE.fullmatch(digest):
            fail("LINUX_PACKAGE_CONTENT_INVALID", f"RPM file {path} has no SHA-256 digest")
        if entry_type == "file" and (inode != 0 or device != 0):
            identity = (device, inode)
            existing = hardlink_identities.get(identity)
            if existing is not None:
                fail(
                    "LINUX_PACKAGE_CONTENT_INVALID",
                    f"RPM payload hardlinks are forbidden: {existing} and {path}",
                )
            hardlink_identities[identity] = path
        entries.append(
            {
                "path": path,
                "type": entry_type,
                "mode": f"{complete_mode & 0o7777:04o}",
                "owner": owner,
                "group": group,
                "size": size,
                "sha256": digest.lower(),
                "linkTarget": link_target,
            }
        )
    entries.sort(key=lambda item: item["path"])
    scripts = inspect_rpm_scripts(package)
    inspect_rpm_semantics(package, package_name, version, architecture)
    return {
        "packageName": package_name,
        "packageVersion": version,
        "architecture": architecture,
        "dependencies": parse_rpm_dependencies(dependency_metadata),
        "entries": entries,
        "scripts": scripts,
    }


def inspect_package(kind: str, package: Path, expected_name: str, expected_architecture: str) -> dict[str, Any]:
    if kind == "deb":
        return inspect_deb_package(package, expected_name, expected_architecture)
    if kind == "rpm":
        return inspect_rpm_package(package, expected_name, expected_architecture)
    fail("LINUX_PACKAGE_KIND_INVALID", f"unsupported package kind {kind}")


def package_entry_map(package_details: dict[str, Any]) -> dict[str, dict[str, Any]]:
    entries = package_details.get("entries")
    if not isinstance(entries, list):
        fail("LINUX_PACKAGE_CONTENT_INVALID", "package entries are missing")
    result: dict[str, dict[str, Any]] = {}
    for entry in entries:
        if not isinstance(entry, dict) or not isinstance(entry.get("path"), str):
            fail("LINUX_PACKAGE_CONTENT_INVALID", "package entry is malformed")
        if entry["path"] in result:
            fail("LINUX_PACKAGE_CONTENT_INVALID", f"duplicate package path {entry['path']}")
        result[entry["path"]] = entry
    return result


def verify_package_dependencies(
    package_details: dict[str, Any],
    policy: dict[str, Any],
    kind: str,
) -> dict[str, list[str]]:
    dependencies = package_details.get("dependencies")
    if not isinstance(dependencies, dict):
        fail("LINUX_PACKAGE_DEPENDENCY_INVALID", "package dependency metadata is missing")
    require_exact_keys(
        dependencies,
        {"requirements", "directPackages"},
        f"packageDependencies.{kind}",
    )
    requirements = dependencies.get("requirements")
    direct_packages = dependencies.get("directPackages")
    if (
        not isinstance(requirements, list)
        or any(not isinstance(item, str) or not item for item in requirements)
        or not isinstance(direct_packages, list)
        or any(not isinstance(item, str) or not item for item in direct_packages)
    ):
        fail("LINUX_PACKAGE_DEPENDENCY_INVALID", "package dependency evidence is malformed")
    reparsed = (
        parse_deb_dependencies(", ".join(requirements))
        if kind == "deb"
        else parse_rpm_dependencies("\n".join(requirements))
    )
    if reparsed != dependencies:
        fail("LINUX_PACKAGE_DEPENDENCY_INVALID", "package dependency evidence is not canonical")
    required = policy["packageDependencies"][kind]
    if kind == "deb":
        expected = parse_deb_dependencies(", ".join(required))
        if dependencies != expected:
            fail(
                "LINUX_PACKAGE_DEPENDENCY_INVALID",
                "DEB Depends must exactly equal the fixed direct dependency list",
            )
    else:
        if len(requirements) != len(set(requirements)):
            fail("LINUX_PACKAGE_DEPENDENCY_INVALID", "RPM Requires contains duplicates")
        required_set = set(required)
        requirement_set = set(requirements)
        missing = sorted(required_set - requirement_set)
        if missing:
            fail(
                "LINUX_PACKAGE_DEPENDENCY_MISSING",
                f"rpm package metadata is missing direct dependencies {missing}",
            )
        if "/bin/sh" not in requirement_set:
            fail(
                "LINUX_PACKAGE_DEPENDENCY_MISSING",
                "RPM package metadata must require the pinned scriptlet interpreter /bin/sh",
            )
        unexpected = sorted(
            requirement_set - required_set - RPM_ALLOWED_AUTOGENERATED_REQUIREMENTS
        )
        if unexpected:
            fail(
                "LINUX_PACKAGE_DEPENDENCY_INVALID",
                f"RPM Requires contains unreviewed dependencies {unexpected}",
            )
    return {
        "required": list(required),
        "packageMetadata": list(requirements),
    }


def package_payload_allowed_paths(policy: dict[str, Any]) -> tuple[set[str], set[str]]:
    allowed_files = {
        *(policy["installedArtifacts"][role]["path"] for role in ROLE_NAMES),
        *policy["packagePayload"]["desktopFiles"],
        *policy["packagePayload"]["iconFiles"],
    }
    allowed_directories: set[str] = set()
    for path in allowed_files:
        parent = PurePosixPath(path).parent
        while parent != PurePosixPath("/"):
            allowed_directories.add(str(parent))
            parent = parent.parent
    return allowed_files, allowed_directories


def verify_package_payload(package_details: dict[str, Any], policy: dict[str, Any]) -> None:
    entries = package_entry_map(package_details)
    allowed_files, allowed_directories = package_payload_allowed_paths(policy)
    for path, entry in entries.items():
        require_exact_keys(
            entry,
            {"path", "type", "mode", "owner", "group", "size", "sha256", "linkTarget"},
            f"packagePayload[{path}]",
        )
        if normalize_package_path(path) != path:
            fail("LINUX_PACKAGE_CONTENT_INVALID", f"package path is not canonical: {path}")
        entry_type = string_value(entry, "type", f"packagePayload[{path}]")
        if entry_type not in {"file", "directory"}:
            fail(
                "LINUX_PACKAGE_CONTENT_INVALID",
                f"package payload {path} has forbidden type {entry_type}",
            )
        expected_type = "file" if path in allowed_files else "directory" if path in allowed_directories else None
        if expected_type is None:
            fail("LINUX_PACKAGE_CONTENT_INVALID", f"package payload path is not allowlisted: {path}")
        if entry_type != expected_type:
            fail("LINUX_PACKAGE_CONTENT_INVALID", f"package payload {path} must be a {expected_type}")
        mode_text = string_value(entry, "mode", f"packagePayload[{path}]")
        if not re.fullmatch(r"0[0-7]{3}", mode_text):
            fail("LINUX_PACKAGE_CONTENT_INVALID", f"package payload {path} has an invalid mode")
        mode = int(mode_text, 8)
        if mode & (stat.S_ISUID | stat.S_ISGID):
            fail("LINUX_PACKAGE_CONTENT_INVALID", f"package payload {path} carries setuid/setgid bits")
        if mode & (stat.S_IWGRP | stat.S_IWOTH):
            fail("LINUX_PACKAGE_CONTENT_INVALID", f"package payload {path} is group/world-writable")
        if str(entry.get("owner")) not in {"0", "root"} or str(entry.get("group")) not in {"0", "root"}:
            fail("LINUX_PACKAGE_CONTENT_INVALID", f"package payload {path} must be root:root")
        size = entry.get("size")
        if isinstance(size, bool) or not isinstance(size, int) or size < 0:
            fail("LINUX_PACKAGE_CONTENT_INVALID", f"package payload {path} has an invalid size")
        digest = entry.get("sha256")
        link_target = entry.get("linkTarget")
        if not isinstance(digest, str) or not isinstance(link_target, str) or link_target:
            fail("LINUX_PACKAGE_CONTENT_INVALID", f"package payload {path} has invalid link metadata")
        if entry_type == "file":
            if size <= 0 or not SHA256_RE.fullmatch(digest):
                fail("LINUX_PACKAGE_CONTENT_INVALID", f"package file {path} must be non-empty with a SHA-256")
        elif size != 0 or digest:
            fail("LINUX_PACKAGE_CONTENT_INVALID", f"package directory {path} carries unexpected content metadata")

    missing_files = sorted(allowed_files - set(entries))
    if missing_files:
        fail("LINUX_PACKAGE_CONTENT_INVALID", f"package payload is missing fixed files {missing_files}")


def verify_package_scripts(
    package_details: dict[str, Any],
    policy: dict[str, Any],
    kind: str,
) -> dict[str, Any]:
    scripts = package_details.get("scripts")
    if not isinstance(scripts, dict):
        fail("LINUX_PACKAGE_SCRIPT_INVALID", "package script evidence is missing")
    mapping = policy["packageScripts"]["mappings"][kind]
    if set(scripts) != set(mapping):
        fail(
            "LINUX_PACKAGE_SCRIPT_INVALID",
            f"{kind} scriptlets differ: missing={sorted(set(mapping) - set(scripts))}, "
            f"extra={sorted(set(scripts) - set(mapping))}",
        )
    verified_phases: dict[str, Any] = {}
    for phase, logical_name in mapping.items():
        evidence = scripts.get(phase)
        if not isinstance(evidence, dict):
            fail("LINUX_PACKAGE_SCRIPT_INVALID", f"{kind} {phase} script evidence is malformed")
        require_exact_keys(
            evidence,
            {"rawSha256", "normalizedSha256", "size", "interpreter"},
            f"packageScripts.{kind}.{phase}",
        )
        raw_sha256 = string_value(evidence, "rawSha256", f"packageScripts.{kind}.{phase}").lower()
        normalized_sha256 = string_value(
            evidence,
            "normalizedSha256",
            f"packageScripts.{kind}.{phase}",
        ).lower()
        size = integer_value(evidence, "size", f"packageScripts.{kind}.{phase}")
        interpreter = string_value(evidence, "interpreter", f"packageScripts.{kind}.{phase}")
        if not SHA256_RE.fullmatch(raw_sha256) or not SHA256_RE.fullmatch(normalized_sha256) or size <= 0:
            fail("LINUX_PACKAGE_SCRIPT_INVALID", f"{kind} {phase} script evidence is invalid")
        definition = policy["packageScripts"]["definitions"][logical_name]
        if raw_sha256 != definition["rawSha256"][kind].lower():
            fail("LINUX_PACKAGE_SCRIPT_MISMATCH", f"{kind} {phase} raw bytes differ from fixed {logical_name}")
        if normalized_sha256 != definition["normalizedSha256"].lower():
            fail("LINUX_PACKAGE_SCRIPT_MISMATCH", f"{kind} {phase} normalized bytes differ from fixed {logical_name}")
        if interpreter != policy["packageScripts"]["interpreter"]:
            fail("LINUX_PACKAGE_SCRIPT_MISMATCH", f"{kind} {phase} interpreter differs from fixed policy")
        verified_phases[phase] = {
            "logicalName": logical_name,
            "rawSha256": raw_sha256,
            "normalizedSha256": normalized_sha256,
            "size": size,
            "interpreter": interpreter,
        }
    return {
        "normalization": policy["packageScripts"]["normalization"],
        "phases": verified_phases,
    }


def canonical_json_sha256(value: Any) -> str:
    encoded = json.dumps(value, sort_keys=True, separators=(",", ":")).encode("utf-8")
    return hashlib.sha256(encoded).hexdigest()


def verify_package_artifact_binding(
    package_details: dict[str, Any],
    installed: dict[str, StableFile],
    policy: dict[str, Any],
) -> None:
    entries = package_entry_map(package_details)
    for role in ROLE_NAMES:
        contract = policy["installedArtifacts"][role]
        path = contract["path"]
        entry = entries.get(path)
        if entry is None:
            fail("LINUX_PACKAGE_CONTENT_INVALID", f"package does not contain fixed {role} path {path}")
        if entry.get("type") != "file" or entry.get("sha256", "").lower() != installed[role].sha256.lower():
            fail("LINUX_PACKAGE_CONTENT_MISMATCH", f"package {role} bytes differ from the installed artifact")
        if entry.get("size") != installed[role].size:
            fail("LINUX_PACKAGE_CONTENT_MISMATCH", f"package {role} size differs from the installed artifact")
        if entry.get("mode") != contract["mode"]:
            fail("LINUX_PACKAGE_CONTENT_MISMATCH", f"package {role} mode differs from fixed policy")
        if str(entry.get("owner")) not in {"0", "root"} or str(entry.get("group")) not in {"0", "root"}:
            fail("LINUX_PACKAGE_CONTENT_MISMATCH", f"package {role} is not root:root")


def ensure_directory_tree(path: Path) -> None:
    path = absolute_path(path)
    current = Path(path.anchor)
    for component in path.parts[1:]:
        current /= component
        try:
            metadata = os.lstat(current)
        except FileNotFoundError:
            try:
                os.mkdir(current, 0o755)
            except FileExistsError:
                pass
            except OSError as error:
                fail("LINUX_PACKAGE_MANIFEST_PATH_INVALID", f"cannot create output directory {current}: {error}")
            try:
                metadata = os.lstat(current)
            except OSError as error:
                fail("LINUX_PACKAGE_MANIFEST_PATH_INVALID", f"cannot inspect output directory {current}: {error}")
        if stat.S_ISLNK(metadata.st_mode) or not stat.S_ISDIR(metadata.st_mode):
            fail("LINUX_PACKAGE_MANIFEST_PATH_INVALID", f"output directory component is not a real directory: {current}")


def write_json_atomic(path: Path, value: dict[str, Any]) -> StableFile:
    path = absolute_path(path)
    ensure_directory_tree(path.parent)
    ensure_no_symlink_components(path.parent, "package manifest directory")
    try:
        existing = os.lstat(path)
    except FileNotFoundError:
        existing = None
    if existing is not None and not stat.S_ISREG(existing.st_mode):
        fail("LINUX_PACKAGE_MANIFEST_PATH_INVALID", "refusing to replace a non-regular package manifest")
    encoded = (json.dumps(value, sort_keys=True, indent=2, separators=(",", ": ")) + "\n").encode("utf-8")
    temporary_name: str | None = None
    try:
        with tempfile.NamedTemporaryFile(prefix=f".{path.name}.", dir=path.parent, delete=False) as output:
            temporary_name = output.name
            os.fchmod(output.fileno(), 0o644)
            output.write(encoded)
            output.flush()
            os.fsync(output.fileno())
        os.replace(temporary_name, path)
        temporary_name = None
        directory_fd = os.open(path.parent, os.O_RDONLY | getattr(os, "O_CLOEXEC", 0))
        try:
            os.fsync(directory_fd)
        finally:
            os.close(directory_fd)
    except OSError as error:
        fail("LINUX_PACKAGE_MANIFEST_WRITE_FAILED", f"cannot publish package manifest: {error}")
    finally:
        if temporary_name is not None:
            try:
                os.unlink(temporary_name)
            except FileNotFoundError:
                pass
    return read_stable_file(path, "generated package manifest", max_bytes=64 * 1024 * 1024)


def verify_release(
    manifest_path: Path,
    *,
    policy_path: Path,
    signature_verifier: Callable[[str, Path, Path | None, Path, str], str] | None = None,
    package_inspector: Callable[[str, Path, str, str], dict[str, Any]] = inspect_package,
    installed_inspector: Callable[[Path, str, dict[str, Any]], StableFile] = inspect_installed_artifact,
) -> dict[str, Any]:
    manifest, manifest_evidence = load_json(manifest_path, "Linux release manifest")
    policy, policy_evidence = load_json(policy_path, "Linux release policy")
    validate_policy(policy)
    validate_manifest(manifest, policy, lint=False)
    if not manifest["captureReleaseEnabled"]:
        fail("LINUX_CAPTURE_RELEASE_DISABLED", "captureReleaseEnabled is false")
    if policy["configurationState"] != "configured":
        fail("LINUX_RELEASE_POLICY_UNCONFIGURED", "fixed Linux release identity and architecture policy is unconfigured")
    git_commit = manifest["gitCommit"]
    build_id = manifest["buildId"]
    if not COMMIT_RE.fullmatch(git_commit) or not BUILD_ID_RE.fullmatch(build_id):
        fail("LINUX_BUILD_IDENTITY_INVALID", "gitCommit or buildId is invalid")

    manifest_directory = manifest_evidence.path.parent
    package_config = manifest["package"]
    signature_config = package_config["signature"]
    kind = package_config["kind"]
    package_path = resolve_manifest_file(manifest_directory, package_config["path"], "package.path")
    public_key_path = resolve_manifest_file(
        manifest_directory,
        signature_config["publicKeyPath"],
        "package.signature.publicKeyPath",
    )
    detached_signature_path = (
        resolve_manifest_file(manifest_directory, signature_config["path"], "package.signature.path")
        if kind == "deb"
        else None
    )
    expected_fingerprint = normalize_fingerprint(
        policy["packageSignatures"][kind]["signerFingerprint"],
        f"releasePolicy.packageSignatures.{kind}",
    )
    signature_evidence: StableFile | None = None
    with tempfile.TemporaryDirectory(
        prefix="taomni-linux-gate-inputs-", dir="/tmp"
    ) as snapshot_directory_text:
        snapshot_directory = Path(snapshot_directory_text)
        os.chmod(snapshot_directory, 0o700)
        package_evidence, package_snapshot = snapshot_stable_file(
            package_path,
            "release package",
            snapshot_directory,
            "package.bin",
        )
        verify_expected_hash(package_evidence, package_config["sha256"], "release package")
        public_key_evidence, public_key_snapshot = snapshot_stable_file(
            public_key_path,
            "release signing public key",
            snapshot_directory,
            "release-key.asc",
            max_bytes=MAX_POLICY_BYTES,
        )
        verify_expected_hash(
            public_key_evidence,
            signature_config["publicKeySha256"],
            "release signing public key",
        )
        detached_signature_snapshot: Path | None = None
        if detached_signature_path is not None:
            signature_evidence, detached_signature_snapshot = snapshot_stable_file(
                detached_signature_path,
                "detached package signature",
                snapshot_directory,
                "package-signature.asc",
                max_bytes=MAX_POLICY_BYTES,
            )
            verify_expected_hash(
                signature_evidence,
                signature_config["sha256"],
                "detached package signature",
            )

        key_fingerprint = openpgp_primary_fingerprint(public_key_snapshot)
        if key_fingerprint != expected_fingerprint:
            fail("LINUX_PACKAGE_SIGNER_MISMATCH", "supplied public key differs from fixed policy")
        if signature_verifier is None:
            if kind == "deb":
                assert detached_signature_snapshot is not None
                verified_fingerprint = verify_deb_signature(
                    package_snapshot,
                    detached_signature_snapshot,
                    public_key_snapshot,
                    expected_fingerprint,
                )
            else:
                verified_fingerprint = verify_rpm_signature(
                    package_snapshot,
                    public_key_snapshot,
                    expected_fingerprint,
                )
        else:
            verified_fingerprint = signature_verifier(
                kind,
                package_snapshot,
                detached_signature_snapshot,
                public_key_snapshot,
                expected_fingerprint,
            )
        if normalize_fingerprint(verified_fingerprint, "verified package signer") != expected_fingerprint:
            fail("LINUX_PACKAGE_SIGNER_MISMATCH", "verified package signer differs from fixed policy")
        package_details = package_inspector(
            kind,
            package_snapshot,
            policy["packageName"],
            manifest["architecture"],
        )

    installed: dict[str, StableFile] = {}
    for role in ROLE_NAMES:
        contract = policy["installedArtifacts"][role]
        installed[role] = installed_inspector(Path(contract["path"]), role, contract)
    helper_policy_content = installed["helperPolicy"].content
    polkit_content = installed["polkitAction"].content
    if helper_policy_content is None or polkit_content is None:
        fail("LINUX_ARTIFACT_UNREADABLE", "installed policy artifacts were not captured")
    verify_helper_policy(
        helper_policy_content,
        policy["helperPolicy"],
        installed["application"].sha256,
        installed["helper"].sha256,
    )
    verify_polkit_action(polkit_content, policy["polkit"])

    verified_package_dependencies = verify_package_dependencies(package_details, policy, kind)
    verify_package_payload(package_details, policy)
    verify_package_artifact_binding(package_details, installed, policy)
    verified_package_scripts = verify_package_scripts(package_details, policy, kind)
    package_scripts_sha256 = canonical_json_sha256(verified_package_scripts)

    # Snapshot use prevents mixed A/B verification. Bind the receipt paths back
    # to the exact source inodes and metadata that produced those snapshots.
    verify_source_unchanged(package_path, package_evidence, "release package")
    verify_source_unchanged(public_key_path, public_key_evidence, "signing public key")
    if detached_signature_path is not None and signature_evidence is not None:
        verify_source_unchanged(
            detached_signature_path,
            signature_evidence,
            "detached signature",
        )
    verify_source_unchanged(manifest_evidence.path, manifest_evidence, "release manifest")
    verify_source_unchanged(policy_evidence.path, policy_evidence, "release policy")
    for role in ROLE_NAMES:
        rechecked = installed_inspector(Path(policy["installedArtifacts"][role]["path"]), role, policy["installedArtifacts"][role])
        if rechecked.sha256 != installed[role].sha256:
            fail("LINUX_ARTIFACT_CHANGED", f"installed {role} changed during release verification")

    package_manifest = {
        "schemaVersion": PACKAGE_MANIFEST_SCHEMA_VERSION,
        "manifestKind": "sockscap_linux_package",
        "platform": PLATFORM,
        "architecture": manifest["architecture"],
        "captureProvider": manifest["captureProvider"],
        "packageKind": kind,
        "packageName": package_details["packageName"],
        "packageVersion": package_details["packageVersion"],
        "packageSha256": package_evidence.sha256,
        "signatureScheme": signature_config["scheme"],
        "signerFingerprint": expected_fingerprint,
        "signatureSha256": (
            signature_evidence.sha256 if signature_evidence is not None else package_evidence.sha256
        ),
        "signingPublicKeySha256": public_key_evidence.sha256,
        "packageDependencies": verified_package_dependencies,
        "entries": package_details["entries"],
        "packageScripts": verified_package_scripts,
        "packageScriptsSha256": package_scripts_sha256,
        "verificationScope": "same_host_installed_fixed_paths",
        "externalEvidenceRequired": ["native_install_lab_provenance"],
    }
    package_manifest_path = resolve_manifest_file(
        manifest_directory,
        manifest["packageManifestOutput"],
        "packageManifestOutput",
    )
    protected_inputs = {manifest_evidence.path, policy_evidence.path, package_path, public_key_path}
    if detached_signature_path is not None:
        protected_inputs.add(detached_signature_path)
    if package_manifest_path in protected_inputs:
        fail("LINUX_PACKAGE_MANIFEST_PATH_INVALID", "package manifest output collides with a verifier input")
    package_manifest_evidence = write_json_atomic(package_manifest_path, package_manifest)

    receipt: dict[str, Any] = {
        "gateSchemaVersion": RECEIPT_SCHEMA_VERSION,
        "gateKind": "sockscap_linux_artifact",
        "platform": PLATFORM,
        "mode": "release",
        "result": "PASS",
        "architecture": manifest["architecture"],
        "captureProvider": manifest["captureProvider"],
        "capturePackageKinds": policy["capturePackageKinds"],
        "appImageCaptureDisabled": policy["appImageCaptureDisabled"],
        "verificationScope": "same_host_installed_fixed_paths",
        "externalEvidenceRequired": ["native_install_lab_provenance"],
        "gitCommit": git_commit.lower(),
        "buildId": build_id,
        "releasePolicySchemaVersion": POLICY_SCHEMA_VERSION,
        "releasePolicySha256": policy_evidence.sha256,
        "artifactManifestPath": os.fspath(manifest_evidence.path),
        "artifactManifestSha256": manifest_evidence.sha256,
        "packageKind": kind,
        "packageVersion": package_details["packageVersion"],
        "packagePath": os.fspath(package_path),
        "packageSha256": package_evidence.sha256,
        "packageSignatureScheme": signature_config["scheme"],
        "packageSignerFingerprint": expected_fingerprint,
        # RPM carries its OpenPGP signature inside the package, so its
        # signature artifact is intentionally the exact package file.
        "signaturePath": os.fspath(detached_signature_path or package_path),
        "signatureSha256": (
            signature_evidence.sha256 if signature_evidence is not None else package_evidence.sha256
        ),
        "packageSigningPublicKey": os.fspath(public_key_path),
        "packageSigningPublicKeySha256": public_key_evidence.sha256,
        "packageDependencies": verified_package_dependencies,
        "packageManifestPath": os.fspath(package_manifest_path),
        "packageManifestSha256": package_manifest_evidence.sha256,
        "packageScriptsSha256": package_scripts_sha256,
        "application": os.fspath(installed["application"].path),
        "applicationSha256": installed["application"].sha256,
        "helper": os.fspath(installed["helper"].path),
        "helperSha256": installed["helper"].sha256,
        "helperPolicy": os.fspath(installed["helperPolicy"].path),
        "helperPolicySha256": installed["helperPolicy"].sha256,
        "polkitAction": os.fspath(installed["polkitAction"].path),
        "polkitActionSha256": installed["polkitAction"].sha256,
        "packageSignatureVerified": True,
        "packagePayloadVerified": True,
        "packageDependenciesVerified": True,
        "packageScriptsVerified": True,
        "helperOwnershipVerified": True,
        "helperPolicyVerified": True,
        "polkitActionVerified": True,
    }
    return receipt


def lint_manifest(manifest_path: Path, *, policy_path: Path) -> dict[str, Any]:
    manifest, manifest_evidence = load_json(manifest_path, "Linux release manifest")
    policy, policy_evidence = load_json(policy_path, "Linux release policy")
    validate_policy(policy)
    validate_manifest(manifest, policy, lint=True)
    return {
        "gateSchemaVersion": RECEIPT_SCHEMA_VERSION,
        "gateKind": "sockscap_linux_artifact",
        "platform": PLATFORM,
        "mode": "lint",
        "captureReleaseEnabled": manifest["captureReleaseEnabled"],
        "capturePackageKinds": policy["capturePackageKinds"],
        "appImageCaptureDisabled": policy["appImageCaptureDisabled"],
        "releasePolicySchemaVersion": POLICY_SCHEMA_VERSION,
        "releasePolicyConfigurationState": policy["configurationState"],
        "releasePolicySha256": policy_evidence.sha256,
        "artifactManifestPath": os.fspath(manifest_evidence.path),
        "artifactManifestSha256": manifest_evidence.sha256,
        "result": "PASS",
    }


def committed_policy_path() -> Path:
    return Path(__file__).resolve().parents[2] / "src-tauri" / "platform" / "sockscap" / "linux" / "release-policy.json"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--lint", action="store_true", help="validate source contracts only")
    parser.add_argument("manifest", type=Path, help="Linux release manifest")
    args = parser.parse_args(argv)
    try:
        if args.lint:
            receipt = lint_manifest(args.manifest, policy_path=committed_policy_path())
        else:
            receipt = verify_release(args.manifest, policy_path=committed_policy_path())
    except LinuxGateError as error:
        print(f"{error.code}: {error.message}", file=sys.stderr)
        return 1
    print(json.dumps(receipt, sort_keys=True, separators=(",", ":")))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
