use super::{Tool, ToolDescriptor, ToolResult};
use crate::ai::shell_safety::check_blacklist;
use async_trait::async_trait;

/// Preview a shell command without executing it (dry_run=true by default).
pub struct RunInTerminalTool;

#[async_trait]
impl Tool for RunInTerminalTool {
    fn descriptor(&self) -> ToolDescriptor {
        ToolDescriptor {
            name: "run_in_terminal",
            description: "在指定会话的终端中执行命令。dry_run=true 时只返回命令文本，不执行。",
            params: "session_id: string, command: string, dry_run?: bool (default true)",
        }
    }

    async fn execute(&self, args: &serde_json::Value) -> ToolResult {
        let command = match args.get("command").and_then(|v| v.as_str()) {
            Some(c) => c.to_string(),
            None => return ToolResult::err("run_in_terminal", "command is required"),
        };
        let dry_run = args
            .get("dry_run")
            .and_then(|v| v.as_bool())
            .unwrap_or(true);

        // Always run blacklist check.
        let safety = check_blacklist(&command);
        if safety.blocked {
            return ToolResult::err(
                "run_in_terminal",
                format!("Blocked: {}", safety.reason.unwrap_or_default()),
            );
        }

        if dry_run {
            ToolResult::ok(
                "run_in_terminal",
                format!("[dry-run] Would execute: {}", command),
            )
        } else {
            // Actual execution is handled by the frontend after user confirmation.
            // The agent backend only returns the command; the frontend calls write_terminal.
            ToolResult::ok("run_in_terminal", format!("EXECUTE:{}", command))
        }
    }

    fn dry_run_preview(&self, args: &serde_json::Value) -> Option<String> {
        args.get("command")
            .and_then(|v| v.as_str())
            .map(|c| c.to_string())
    }
}

/// Read the last N lines of terminal output (requires user_invoked=true).
pub struct ReadTerminalTailTool;

#[async_trait]
impl Tool for ReadTerminalTailTool {
    fn descriptor(&self) -> ToolDescriptor {
        ToolDescriptor {
            name: "read_terminal_tail",
            description:
                "读取当前活跃终端最近 N 行输出。仅用户在 'AI 解释报错' 流程中显式触发时可用。",
            params: "session_id: string, lines?: u32 (default 50), user_invoked: bool",
        }
    }

    async fn execute(&self, args: &serde_json::Value) -> ToolResult {
        let user_invoked = args
            .get("user_invoked")
            .and_then(|v| v.as_bool())
            .unwrap_or(false);
        if !user_invoked {
            return ToolResult::err("read_terminal_tail", "user_invoked must be true");
        }
        // Actual terminal content is passed in by the frontend when user_invoked=true.
        // The agent receives it as a pre-filled context string.
        let content = args.get("content").and_then(|v| v.as_str()).unwrap_or("");
        ToolResult::ok("read_terminal_tail", content.to_string())
    }
}

/// Explain a terminal error message.
pub struct ExplainErrorTool;

#[async_trait]
impl Tool for ExplainErrorTool {
    fn descriptor(&self) -> ToolDescriptor {
        ToolDescriptor {
            name: "explain_error",
            description: "解释一段终端输出（错误信息），给出原因和建议修复步骤",
            params: "text: string",
        }
    }

    async fn execute(&self, args: &serde_json::Value) -> ToolResult {
        let text = args.get("text").and_then(|v| v.as_str()).unwrap_or("");
        // The actual explanation is generated by the LLM in the agent loop.
        // This tool just passes the text through as context.
        ToolResult::ok("explain_error", format!("EXPLAIN:{}", text))
    }
}
