#!/usr/bin/env python3
"""Render references/testid-catalog.md from feature.controls.

The legacy catalog was hand-maintained and drifted whenever someone added a
testid in source without remembering to update the doc. Now that
`feature-list.md` is the authoritative source for every interactive /
display selector the test suite knows about, the catalog is just a
projection of that data.

Usage:
    python -m qa_ui_auto.gen_testid_catalog                  # write to default path
    python -m qa_ui_auto.gen_testid_catalog --stdout         # print, don't touch disk
    python -m qa_ui_auto.gen_testid_catalog --check          # exit 1 if file is stale

Output layout:
    # Taomni UI testid catalog (auto-generated)
    > Generated by `python -m qa_ui_auto.gen_testid_catalog` from
    > qa-ui-auto-tests/feature-list.md. Do not edit manually — change the
    > feature's `controls:` block instead and re-run the generator.

    ## main / window  (F1.3)
    - `[data-testid="app-titlebar"]` — display — F1.3 titlebar
    - `[data-testid="window-min"]` — interactive — F1.3 window-min

Grouped by feature area (the `area:` field in the frontmatter); features
sharing an area come together. Backend-only and feature-without-controls
entries are skipped — they have no DOM surface to document.
"""

from __future__ import annotations

import argparse
import sys
from collections import defaultdict
from pathlib import Path

HERE = Path(__file__).resolve().parent
SCRIPTS_DIR = HERE.parent
if str(SCRIPTS_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPTS_DIR))

from qa_ui_auto.feature_catalog import load_features, Feature, Control  # noqa: E402

DEFAULT_OUTPUT = Path(".agents/skills/qa-ui-auto/references/testid-catalog.md")
HEADER = """\
# Taomni UI testid catalog (auto-generated)

> Generated by `python -m qa_ui_auto.gen_testid_catalog` from
> `qa-ui-auto-tests/feature-list.md`. Do **not** edit manually — change the
> feature's `controls:` block instead and re-run the generator.
>
> Each line lists `selector — kind — F{feature}.{control_id}`. Optional
> controls (only render under conditions) are marked with `[optional]`.
> Aliases are listed underneath the primary selector indented with `↳`.

"""


def _area_label(f: Feature) -> str:
    if not f.area:
        return f"_misc ({f.id})"
    return f"{f.area} ({f.id})"


def render(features: list[Feature]) -> str:
    # Skip features without controls — backend-only, logical-only, or not yet
    # filled in.
    interesting = [f for f in features if f.controls]
    by_area: dict[str, list[Feature]] = defaultdict(list)
    for f in interesting:
        by_area[_area_label(f)].append(f)
    out: list[str] = [HEADER.rstrip()]
    out.append("")
    for area in sorted(by_area):
        out.append(f"## {area}")
        out.append("")
        for f in by_area[area]:
            for c in f.controls:
                tag = c.kind
                if c.optional:
                    tag = f"{tag} [optional]"
                out.append(f"- `{c.selector}` — {tag} — {f.id}.{c.id}")
                for alias in c.aliases:
                    out.append(f"  ↳ `{alias}` — alias")
        out.append("")
    return "\n".join(out).rstrip() + "\n"


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(prog="qa_ui_auto.gen_testid_catalog")
    ap.add_argument("--features", default="qa-ui-auto-tests/feature-list.md",
                    help="path to feature-list.md (default: %(default)s)")
    ap.add_argument("--out", default=str(DEFAULT_OUTPUT),
                    help="path to write the catalog (default: %(default)s)")
    ap.add_argument("--stdout", action="store_true",
                    help="print to stdout instead of writing the file")
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if the file on disk doesn't match what would "
                         "be generated. Use as a CI guard.")
    args = ap.parse_args(argv)

    feats = load_features(Path(args.features))
    rendered = render(feats)

    if args.stdout:
        sys.stdout.write(rendered)
        return 0

    target = Path(args.out)
    if args.check:
        if not target.exists():
            print(f"check: target file does not exist: {target}", file=sys.stderr)
            return 1
        existing = target.read_text(encoding="utf-8")
        if existing != rendered:
            print(
                f"check: {target} is out of date. Run "
                "`python -m qa_ui_auto.gen_testid_catalog` to regenerate.",
                file=sys.stderr,
            )
            return 1
        print(f"check: {target} is up to date.")
        return 0

    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(rendered, encoding="utf-8")
    print(f"wrote {target} ({len(rendered.splitlines())} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
