/**
 * IntelliJ IDEA Ultimate 2026.2.2 (IU-262.10315.125) "Default for XWin" keymap
 * (parent "$default"), extracted from
 * lib/intellij.platform.ide.impl.jar!/keymaps/{$default,Default for XWin}.xml
 * for the Taomni actions that have an IDEA counterpart (ED-PARITY-013 A4.2).
 * Labels use Taomni's shared shortcut formatter vocabulary.
 * Generated; do not hand-edit the bindings.
 */
export interface IdeaKeymapEntry {
  taomniActionId: string;
  ideaActionId: string;
  ideaBindings: readonly string[];
}

export const IDEA_XWIN_KEYMAP: readonly IdeaKeymapEntry[] = [
  { taomniActionId: "workspace.findAction", ideaActionId: "GotoAction", ideaBindings: ["Ctrl+Shift+A"] },
  { taomniActionId: "workspace.goToFile", ideaActionId: "GotoFile", ideaBindings: ["Ctrl+Shift+N"] },
  { taomniActionId: "workspace.goToClass", ideaActionId: "GotoClass", ideaBindings: ["Ctrl+N"] },
  { taomniActionId: "workspace.goToSymbol", ideaActionId: "GotoSymbol", ideaBindings: ["Ctrl+Alt+Shift+N"] },
  { taomniActionId: "workspace.recentFiles", ideaActionId: "RecentFiles", ideaBindings: ["Ctrl+E"] },
  { taomniActionId: "workspace.recentLocations", ideaActionId: "RecentLocations", ideaBindings: ["Ctrl+Shift+E"] },
  { taomniActionId: "workspace.lastEditLocation", ideaActionId: "JumpToLastChange", ideaBindings: ["Ctrl+Shift+Backspace"] },
  { taomniActionId: "workspace.nextError", ideaActionId: "GotoNextError", ideaBindings: ["F2"] },
  { taomniActionId: "workspace.prevError", ideaActionId: "GotoPreviousError", ideaBindings: ["Shift+F2"] },
  { taomniActionId: "workspace.quickDefinition", ideaActionId: "QuickImplementations", ideaBindings: ["Ctrl+Shift+I"] },
  { taomniActionId: "workspace.parameterInfo", ideaActionId: "ParameterInfo", ideaBindings: ["Ctrl+P"] },
  { taomniActionId: "workspace.editor.copy", ideaActionId: "$Copy", ideaBindings: ["Ctrl+C", "Ctrl+Insert"] },
  { taomniActionId: "workspace.editor.cut", ideaActionId: "$Cut", ideaBindings: ["Ctrl+X", "Shift+Delete"] },
  { taomniActionId: "workspace.editor.paste", ideaActionId: "$Paste", ideaBindings: ["Ctrl+V", "Shift+Insert"] },
  { taomniActionId: "workspace.editor.pasteAsPlainText", ideaActionId: "EditorPasteSimple", ideaBindings: ["Ctrl+Alt+Shift+V"] },
  { taomniActionId: "workspace.editor.copyReference", ideaActionId: "CopyReference", ideaBindings: ["Ctrl+Alt+Shift+C"] },
  { taomniActionId: "editor.pasteFromHistory", ideaActionId: "PasteMultiple", ideaBindings: ["Ctrl+Shift+V", "Ctrl+Shift+Insert"] },
  { taomniActionId: "workspace.editor.moveStatementUp", ideaActionId: "MoveStatementUp", ideaBindings: ["Ctrl+Shift+Up"] },
  { taomniActionId: "workspace.editor.moveStatementDown", ideaActionId: "MoveStatementDown", ideaBindings: ["Ctrl+Shift+Down"] },
  { taomniActionId: "workspace.editor.selectNextOccurrence", ideaActionId: "SelectNextOccurrence", ideaBindings: ["Alt+J"] },
  { taomniActionId: "workspace.editor.selectAllOccurrences", ideaActionId: "SelectAllOccurrences", ideaBindings: ["Ctrl+Alt+Shift+J"] },
  { taomniActionId: "workspace.editor.foldSelection", ideaActionId: "CollapseSelection", ideaBindings: ["Ctrl+."] },
  { taomniActionId: "workspace.editor.foldAll", ideaActionId: "CollapseAllRegions", ideaBindings: ["Ctrl+Shift+NumPad -", "Ctrl+Shift+-"] },
  { taomniActionId: "workspace.editor.unfoldAll", ideaActionId: "ExpandAllRegions", ideaBindings: ["Ctrl+Shift+NumPad +", "Ctrl+Shift+="] },
  { taomniActionId: "workspace.optimizeImports", ideaActionId: "OptimizeImports", ideaBindings: ["Ctrl+Alt+O"] },
  { taomniActionId: "workspace.navigateBack", ideaActionId: "Back", ideaBindings: ["Ctrl+Alt+Left"] },
  { taomniActionId: "workspace.navigateForward", ideaActionId: "Forward", ideaBindings: ["Ctrl+Alt+Right"] },
  { taomniActionId: "workspace.findInFiles", ideaActionId: "FindInPath", ideaBindings: ["Ctrl+Shift+F"] },
  { taomniActionId: "workspace.replaceInFiles", ideaActionId: "ReplaceInPath", ideaBindings: ["Ctrl+Shift+R"] },
  { taomniActionId: "workspace.fileStructure", ideaActionId: "FileStructurePopup", ideaBindings: ["Ctrl+F12"] },
  { taomniActionId: "workspace.format", ideaActionId: "ReformatCode", ideaBindings: ["Ctrl+Alt+L"] },
  { taomniActionId: "workspace.quickDocumentation", ideaActionId: "QuickJavaDoc", ideaBindings: ["Ctrl+Q"] },
  { taomniActionId: "workspace.typeInfo", ideaActionId: "ExpressionTypeInfo", ideaBindings: ["Ctrl+Shift+P"] },
  { taomniActionId: "workspace.codeActions", ideaActionId: "ShowIntentionActions", ideaBindings: ["Alt+Enter"] },
  { taomniActionId: "workspace.gotoTypeDefinition", ideaActionId: "GotoTypeDeclaration", ideaBindings: ["Ctrl+Shift+B"] },
  { taomniActionId: "workspace.gotoImplementation", ideaActionId: "GotoImplementation", ideaBindings: ["Ctrl+Alt+B"] },
  { taomniActionId: "workspace.gotoDeclaration", ideaActionId: "GotoDeclaration", ideaBindings: ["Ctrl+B"] },
  { taomniActionId: "workspace.renameSymbol", ideaActionId: "RenameElement", ideaBindings: ["Shift+F6"] },
  { taomniActionId: "workspace.safeDeleteSymbol", ideaActionId: "SafeDelete", ideaBindings: ["Alt+Delete"] },
  { taomniActionId: "workspace.refactorThis", ideaActionId: "Refactorings.QuickListPopupAction", ideaBindings: ["Ctrl+Alt+Shift+T"] },
  { taomniActionId: "workspace.extractMethod", ideaActionId: "ExtractMethod", ideaBindings: ["Ctrl+Alt+M"] },
  { taomniActionId: "workspace.extractVariable", ideaActionId: "IntroduceVariable", ideaBindings: ["Ctrl+Alt+V"] },
  { taomniActionId: "workspace.inline", ideaActionId: "Inline", ideaBindings: ["Ctrl+Alt+N"] },
  { taomniActionId: "workspace.changeSignature", ideaActionId: "ChangeSignature", ideaBindings: ["Ctrl+F6"] },
  { taomniActionId: "workspace.moveRefactor", ideaActionId: "Move", ideaBindings: ["F6"] },
  { taomniActionId: "workspace.toggleProjectTree", ideaActionId: "ActivateProjectToolWindow", ideaBindings: ["Alt+1"] },
  { taomniActionId: "workspace.restoreToolWindowLayout", ideaActionId: "RestoreDefaultLayout", ideaBindings: ["Shift+F12"] },
  { taomniActionId: "workspace.showProblems", ideaActionId: "ActivateProblemsViewToolWindow", ideaBindings: ["Alt+6"] },
  { taomniActionId: "workspace.callHierarchy", ideaActionId: "CallHierarchy", ideaBindings: ["Ctrl+Alt+H"] },
  { taomniActionId: "workspace.typeHierarchy", ideaActionId: "TypeHierarchy", ideaBindings: ["Ctrl+H"] },
  { taomniActionId: "workspace.findReferences", ideaActionId: "FindUsages", ideaBindings: ["Alt+F7"] },
  { taomniActionId: "workspace.showUsages", ideaActionId: "ShowUsages", ideaBindings: ["Ctrl+Alt+7"] },
  { taomniActionId: "workspace.previousMethod", ideaActionId: "MethodUp", ideaBindings: ["Alt+Up"] },
  { taomniActionId: "workspace.nextMethod", ideaActionId: "MethodDown", ideaBindings: ["Alt+Down"] },
  { taomniActionId: "workspace.toggleBookmark", ideaActionId: "ToggleBookmark", ideaBindings: ["F11"] },
  { taomniActionId: "workspace.toggleBookmarkWithMnemonic", ideaActionId: "ToggleBookmarkWithMnemonic", ideaBindings: ["Ctrl+F11"] },
  { taomniActionId: "workspace.showBookmarks", ideaActionId: "ShowBookmarks", ideaBindings: ["Shift+F11"] },
  { taomniActionId: "workspace.activateNavigationBar", ideaActionId: "ShowNavBar", ideaBindings: ["Alt+Home"] },
  { taomniActionId: "workspace.highlightUsagesInFile", ideaActionId: "HighlightUsagesInFile", ideaBindings: ["Ctrl+Shift+F7"] },
  { taomniActionId: "workspace.nextOccurrence", ideaActionId: "NextOccurence", ideaBindings: ["Ctrl+Alt+Down"] },
  { taomniActionId: "workspace.previousOccurrence", ideaActionId: "PreviousOccurence", ideaBindings: ["Ctrl+Alt+Up"] },
  { taomniActionId: "workspace.toggleRenderedDocComments", ideaActionId: "ToggleRenderedDocPresentation", ideaBindings: ["Ctrl+Alt+Q"] },
  { taomniActionId: "workspace.toggleColumnSelection", ideaActionId: "EditorToggleColumnMode", ideaBindings: ["Alt+Shift+Insert"] },
  { taomniActionId: "workspace.toggleTerminal", ideaActionId: "ActivateTerminalToolWindow", ideaBindings: ["Alt+F12"] },
  { taomniActionId: "workspace.runActiveJavaFile", ideaActionId: "Run", ideaBindings: ["Shift+F10"] },
  { taomniActionId: "workspace.runContextConfiguration", ideaActionId: "RunClass", ideaBindings: ["Ctrl+Shift+F10"] },
  { taomniActionId: "workspace.buildProject", ideaActionId: "CompileDirty", ideaBindings: ["Ctrl+F9"] },
  { taomniActionId: "workspace.recompileActiveFile", ideaActionId: "Compile", ideaBindings: ["Ctrl+Shift+F9"] },
  { taomniActionId: "workspace.toggleBreakpoint", ideaActionId: "ToggleLineBreakpoint", ideaBindings: ["Ctrl+F8"] },
  { taomniActionId: "workspace.viewBreakpoints", ideaActionId: "ViewBreakpoints", ideaBindings: ["Ctrl+Shift+F8"] },
  { taomniActionId: "workspace.showRunTasks", ideaActionId: "ActivateRunToolWindow", ideaBindings: ["Alt+4"] },
  { taomniActionId: "workspace.rerunLastTask", ideaActionId: "Rerun", ideaBindings: ["Ctrl+F5"] },
  { taomniActionId: "workspace.save", ideaActionId: "SaveAll", ideaBindings: ["Ctrl+S"] },
  { taomniActionId: "workspace.closeActiveEditorTab", ideaActionId: "CloseContent", ideaBindings: ["Ctrl+F4"] },
  { taomniActionId: "workspace.revealActiveFileInTree", ideaActionId: "SelectIn", ideaBindings: ["Alt+F1"] },
  { taomniActionId: "workspace.runToCursor", ideaActionId: "RunToCursor", ideaBindings: ["Alt+Shift+9"] },
  { taomniActionId: "editor.replace", ideaActionId: "Replace", ideaBindings: ["Ctrl+R"] },
  { taomniActionId: "editor.expandSelection", ideaActionId: "EditorSelectWord", ideaBindings: ["Ctrl+W"] },
  { taomniActionId: "editor.shrinkSelection", ideaActionId: "EditorUnSelectWord", ideaBindings: ["Ctrl+Shift+W"] },
  { taomniActionId: "editor.toggleLineComment", ideaActionId: "CommentByLineComment", ideaBindings: ["Ctrl+/", "Ctrl+NumPad /"] },
  { taomniActionId: "editor.toggleBlockComment", ideaActionId: "CommentByBlockComment", ideaBindings: ["Ctrl+Shift+/", "Ctrl+Shift+NumPad /"] },
  { taomniActionId: "editor.copyLineDown", ideaActionId: "EditorDuplicate", ideaBindings: ["Ctrl+D"] },
  { taomniActionId: "editor.deleteLine", ideaActionId: "EditorDeleteLine", ideaBindings: ["Ctrl+Y"] },
  { taomniActionId: "editor.moveLineUp", ideaActionId: "MoveLineUp", ideaBindings: ["Alt+Shift+Up"] },
  { taomniActionId: "editor.moveLineDown", ideaActionId: "MoveLineDown", ideaBindings: ["Alt+Shift+Down"] },
  { taomniActionId: "editor.gotoLine", ideaActionId: "GotoLine", ideaBindings: ["Ctrl+G"] },
  { taomniActionId: "editor.completeStatement", ideaActionId: "EditorCompleteStatement", ideaBindings: ["Ctrl+Shift+Enter"] },
  { taomniActionId: "editor.basicCompletion", ideaActionId: "CodeCompletion", ideaBindings: ["Ctrl+Space"] },
  { taomniActionId: "editor.joinLines", ideaActionId: "EditorJoinLines", ideaBindings: ["Ctrl+Shift+J"] },
  { taomniActionId: "editor.unselectLastOccurrence", ideaActionId: "UnselectPreviousOccurrence", ideaBindings: ["Alt+Shift+J"] },
  { taomniActionId: "editor.toggleCase", ideaActionId: "EditorToggleCase", ideaBindings: ["Ctrl+Shift+U"] },
  { taomniActionId: "editor.find", ideaActionId: "Find", ideaBindings: ["Ctrl+F", "Alt+F3"] },
  { taomniActionId: "editor.findNext", ideaActionId: "FindNext", ideaBindings: ["F3", "Ctrl+L"] },
  { taomniActionId: "editor.findPrevious", ideaActionId: "FindPrevious", ideaBindings: ["Shift+F3", "Ctrl+Shift+L"] },
  { taomniActionId: "editor.surroundWith", ideaActionId: "SurroundWith", ideaBindings: ["Ctrl+Alt+Shift+B", "Ctrl+Alt+T"] },
  { taomniActionId: "editor.generateCode", ideaActionId: "Generate", ideaBindings: ["Alt+Insert"] },
  { taomniActionId: "workspace.showSettings", ideaActionId: "ShowSettings", ideaBindings: ["Ctrl+Alt+S"] },
  { taomniActionId: "workspace.jumpToLastToolWindow", ideaActionId: "JumpToLastWindow", ideaBindings: ["F12"] },
  { taomniActionId: "workspace.hideActiveToolWindow", ideaActionId: "HideActiveWindow", ideaBindings: ["Shift+Esc"] },
  { taomniActionId: "workspace.hideAllToolWindows", ideaActionId: "HideAllWindows", ideaBindings: ["Ctrl+Shift+F12"] },
  { taomniActionId: "workspace.toggleDocumentationPane", ideaActionId: "ActivateStructureToolWindow", ideaBindings: ["Alt+7"] },
  { taomniActionId: "workspace.openGit", ideaActionId: "ActivateVersionControlToolWindow", ideaBindings: ["Alt+9"] },
  { taomniActionId: "workspace.toggleTodosPane", ideaActionId: "ActivateBookmarksToolWindow", ideaBindings: ["Alt+2"] },
];
